### ISSUE TITLE
Jail Sometimes Makes Players Invulnerable

### ISSUE THREAD

**Issue by Ruok2bu** [Nayruden/Ulysses#105]
On my TTT server, sometimes if a player is jailed and killed a few times and then unjailed.  The effect persists, if the player is killed again, their body drops to the ground and they respawn in the same place that they died.

**Comment by Nayruden** [comment]
I'm a little late on responding to this one -- but given that it's been two years without anyone saying this is an issue on their server, I'm assuming that it's been fixed or is very rare. If it's still an issue, let us know.
