### ISSUE TITLE
Out of Date Message

### ISSUE THREAD

**Issue by Ruok2bu** [Nayruden/Ulysses#159]
It would be cool if ULX displayed a "ULX is out of date.  Please update it." message to the highest level admin whenever they connect to server.  It would make knowing when to update easier.

Just stick a text file with a version number on the website and check against that to see if the installed ulx/ulib is out of date.

**Comment by SticklyMan** [comment]
Addressed in our new repo -- https://github.com/TeamUlysses/ulx/commit/28a28a206117fcff25839a5f429c855884fc1fdc
