### ISSUE TITLE
UPPL lua error when spawning limited props

### ISSUE THREAD

**Issue by TypicalRookie** [Nayruden/Ulysses#266]
When I spawn a prop that is has a limit on it with uppl_affectadmins 0 the prop will spawn "owned" by the map and I get this lua error

[ERROR] addons/uppl/lua/autorun/server/uppl.lua:82: attempt to index a nil value
  1. CheckModelCount - addons/uppl/lua/autorun/server/uppl.lua:82
   2. fn - addons/uppl/lua/autorun/server/uppl.lua:115
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:183
     4. GMODSpawnProp - gamemodes/sandbox/gamemode/commands.lua:166
      5. unknown - gamemodes/sandbox/gamemode/commands.lua:19
       6. unknown - lua/includes/modules/concommand.lua:69

When I try to spawn a prop that has a limit on it with uppl_affectadmins 1 it will not even spawn and I get the same above lua error.

**Comment by Nayruden** [comment]
It seems that your UniqueId changed during gameplay somehow? Regardless, this hasn't occurred to anyone else in two years, and when I tested it just now it worked fine.
