### ISSUE TITLE
Menu not loading properly when joining

### ISSUE THREAD

**Issue by Cyberuben** [Nayruden/Ulysses#296]
Whenever I join my server, my menu looks somewhat like this:
http://i.imgur.com/K5trzc3.png
Not everyone in a certain group appears, commands don't show (so I can't set permissions using the GUI). I have almost every permission as server_manager (my rank), though, I can't seem to fix this bug. I noticed that if I make changes to ULX in Lua, and then rejoin, it does work though.

**Comment by ganggreen707** [comment]
I have had this problem the day i made the server please , is there any new info on this ??

**Comment by 00875** [comment]
Some of your files are corrupted. Delete ulx and ulib folders in data.

**Comment by Bryantdl7** [comment]
@00875 What you're suggesting is deleting the entire server's existence. 

ulx globalban caused the issue for me I found out; in case that's helpful to anyone.

**Comment by 00875** [comment]
ulx globalban is not listed as standart command. This is not ULX issue.

**Comment by Bryantdl7** [comment]
I realize that, I'm just telling you that addon was giving me the issues.

**Comment by wontonanimalchin** [comment]
Same problem with mine now, someone help please because i have people wanting to be admin and mod

**Comment by MitzelLP** [comment]
I do have the same Problem. I have ulx globalbans installed on my Servers.

**Comment by SticklyMan** [comment]
@Mates is this still occurring on your server as well? If so, I'd like to take a look at it along with the votemap thing.

**Comment by MitzelLP** [comment]
@SticklyMan Yes this error is this still occurring.

**Comment by SticklyMan** [comment]
@Mates @MitzelLP Could you guys update to the latest version and see if this problem has been resolved? I have a hunch that our recent fix might fix this one, but I'd like you guys to confirm it for me. Thanks!

Also, we are moving repositories. To get the latest updates to ULX and ULib, please see this thread:
http://forums.ulyssesmod.net/index.php/topic,9111.0.html

**Comment by Mates** [comment]
@SticklyMan The thing is it seems to happen pretty randomly, but I've tried it couple of times now and it seems to be working so far.

**Comment by SticklyMan** [comment]
@Mates That's fine- I am aware that the issue is hard to replicate (haven't been able to myself), but if you could try it for a week or so and let me know if it comes up at all, that'd be very helpful. :)

I think the issue happens most frequently when you're the first player joining a server after a mapchange.
