### ISSUE TITLE
ragdoll spawn problem (Deathrun)

### ISSUE THREAD

**Issue by darkjacky** [Nayruden/Ulysses#346]
-----------------------------------------------------------------------------------------------------------------------------------------
TEST [lua/includes/modules/json.lua][lua/includes/modules/properties.lua]
TEST [lua/includes/modules/json.lua][lua/includes/modules/halo.lua]

[ERROR] lua/includes/modules/properties.lua:154: attempt to call method 'GetAimVector' (a nil value)
  1. fn - lua/includes/modules/properties.lua:154
   2. Run - addons/ulib/lua/ulib/shared/hook.lua:183
    3. fn - lua/includes/modules/halo.lua:162
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:183
-----------------------------------------------------------------------------------------------------------------------------------------

To reproduce the but all you need is ulx ulib and deathrun.

Then ragdoll a player and make the gamemode respawn the player. And poof error.

if you need more information please tell me.

**Comment by SticklyMan** [comment]
Confirmed bug. There are two issues here:
When the player entity is removed, it really is REMOVED. The player generally can't do anything until they rejoin. I don't know if there's much we can do about this one, except prevent cases where ULX is causing the player entity to be removed (such as ulx ragdoll). This can be easily tested by running: "lua_run player.GetAll()[1]:Remove()"

Next, if a player gets removed, and the server does not restart or changelevel before the player rejoins, then the players rank will be set to (and saved as) user. This smptom is also very likely related to #302.
