### ISSUE TITLE
Jail bug

### ISSUE THREAD

**Issue by Brunodps** [Nayruden/Ulysses#358]
So in the latest darkrp update theres a bug with jails where when someone disconnects the jail doesnt dissapear and its not able to be removed  so it just stays there untill the server restarts.
Is it possible to fix that? 
![804d5f85df385b6d4fc2d1621b1397c0](https://cloud.githubusercontent.com/assets/9210404/4625833/fab63f92-537a-11e4-94f6-4eff44ebb6f5.png)

**Comment by SticklyMan** [comment]
This was likely fixed already, as I could not reproduce. However, we decided to prioritize the hook anyways.
