### ISSUE TITLE
Unauthed player

### ISSUE THREAD

**Issue by Bryantdl7** [Nayruden/Ulysses#366]
[ERROR] Unauthed player
  1. query - [C]:-1
   2. fn - addons/ulx/lua/ulx/xgui/bans.lua:501
    3. fn - addons/ulib/lua/ulib/shared/hook.lua:184
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/modules/net.lua:32

basically all of ulx just killed itself for me for no good reason. ive had it installed for over 6 months .-.

**Comment by SticklyMan** [comment]
The Unauthed player bug is generally caused by conflicting addons, or race conditions during player join. If this is still an issue, please post a new thread on our forums, under help and support, and we can work out a more specific problem. http://forums.ulyssesmod.net/index.php/board,11.0.html
