### ISSUE TITLE
Multiple Bugs/Issues regarding the ULX menu.

### ISSUE THREAD

**Issue by alicethemadd** [Nayruden/Ulysses#370]
There are several issues that are happening on our ULX menu in our server. I've tried to pair each of the issues individually into one big lump, to try to fix the issues that have been persisting since the 25th of October of this year. It didn't exactly work. If you guys would be able to help me fix these issues in a whole, it would make my stress levels go from boiling over to sustainable, atleast. We've done a fresh restart and re-install, and all that through our host, where they removed every single addon and plugin, and put it into a backup, and did a fresh re-install of the ULX menu plugin. The current issues that've been going on since late October are as follows, you probably know what we're talking about on these, but I don't have the slightest idea on how to fix them myself after what we've done to attempt to fix it..:

- The ULX causes the server to lag when someone, or several people join into the server.

- The xgui groups/members in groups doesn't show for some people while it shows for others, and    causes tons of lag and frame rate issues.

- Certain permissions mess up, or conflict with Pointshop, in the sense that some people will lose their permissions (as in when they go to buy something, it says they don't have the permissions to do so). We'll go in and fix them, and then a few days later, the problem does a rinse and repeat cycle.

**Comment by SticklyMan** [comment]
We have not heard of any major lag issues, and we haven't been able to replicate any similar issues since this issue was created. We do have some outstanding issues with XGUI not loading data properly and ranks being lost, which we are trying to track down. Are you guys still having issues? Feel free to contact me on Steam, and I can help with any outstanding issues. http://steamcommunity.com/id/Stickly_Man

**Comment by Nayruden** [comment]
No response in over a week, closing out the issue.

If you're still having problems, let us know! We do care! We are just trying to keep the open issues down to what we know to be issues.
