### ISSUE TITLE
Lag When Uncloaking

### ISSUE THREAD

**Issue by Z0mbine** [Nayruden/Ulysses#380]
I have not changed a single file relating to how cloak works and suddenly on my server, for me and only a few others, when uncloaking we get a massive lag spike. I've already checked to see if it was a conflicting addon, and tried a fresh install, but to no avail.

Is it possible the "Think" hook for doInvis() is causing it?

**Comment by Nayruden** [comment]
We recently made a change to how the cloaking works. I'll assign @SticklyMan to see if it's related.

**Comment by SticklyMan** [comment]
Unable to reproduce- there is only a tiny bit of data sent when a clock/uncloak occurs, and unless it's client-side lag from the engine itself, this is not a ULX issue. If you're still having problems with it, contact me or make a new thread on our forums at forums.ulyssesmod.net, and we can test further.
