### ISSUE TITLE
[Enhancement] Reserved Slots - Disconnect Message

### ISSUE THREAD

**Issue by MuteTM** [Nayruden/Ulysses#383]
When:
- Reserved slots are configured
- All non-reserved slots are full

If a player without reserved slot access joins, they are kicked with "[ULX] Reserved slot, sorry!". Is it possible to add an option to kick them with the default "server full / GameUI_ServerRejectServerFull" message, as the server is technically full?

**Comment by Nayruden** [comment]
Not going to implement this. While it technically works, it does not translate on the server (nor is it able to) and so comes across oddly.
