### ISSUE TITLE
ULX not saving anything anymore. But still works some of the time.

### ISSUE THREAD

**Issue by UnderYouFive** [Nayruden/Ulysses#392]
If I make someone admin, when the map changes they go back to the rank before. And sometimes the has access to doesn't show all the time. -http://i.gyazo.com/7f5a9e2773696e2e33d7fd1a85a3849c.png

**Comment by reper** [comment]
I have the same issue.

I'm using ulx mysql.

I can't see server settings in xgui, bans, people who are in what rank(like his^ picture), rank's permissions, etc.

**Comment by BasonTaylor** [comment]
This Problem is Not Going Away For ME Nor MY Friends Server and A Server Called CASG is Having Trouble with this same Problem thank you for all your work but we need this fixed

**Comment by BasonTaylor** [comment]
But when we join it will happen to one of us but not the other HELP! D:

**Comment by BasonTaylor** [comment]
Same Problem 
My Super Admin or Admin Group Not Showing Up
          URL To PROOF! : http://gyazo.com/2904f4aa47210c052bdcd1aa89fd6e49
My Server Limits Not Showing Up!
          URL To PROOF! : http://gyazo.com/cab51c8edf471b2e68f8b0c784646785
The Server Advert Stuff Gone!
          URL To PROOF! : http://gyazo.com/0c18297acdeebbf39a88754327ab30e0
The Ban List Is Also Gone I have 10 Baned Individuals...
          URL To PROOF! : http://gyazo.com/ea5ae9618a044e557ff9c1a002a0d77b
I Tried Deleting the data Then It came Back After 1 hour Nothing is working i uninstalled it then re installed it nothing

**Comment by UnderYouFive** [comment]
My problem was a server management addon that kept resetting the user back to their old group.

**Comment by UnderYouFive** [comment]
Can you give me a list of ALL of your addons?

**Comment by BasonTaylor** [comment]
yes here
1 http://gyazo.com/0101425e1b918d4710e5702d714d7a3a
2 http://gyazo.com/c66d8aec3cc04873f4f93ad8d84dcafd

**Comment by BasonTaylor** [comment]
and also here
http://steamcommunity.com/sharedfiles/filedetails/?id=394635582

**Comment by BasonTaylor** [comment]
i found the problem Atlis chat

**Comment by UnderYouFive** [comment]
Is your atlas chat up to date?

**Comment by BasonTaylor** [comment]
i have no clue

**Comment by UnderYouFive** [comment]
That would be a problem...

**Comment by BasonTaylor** [comment]
hey im haveing a problem my friend is not able to join and this pops up and
crashes his whole gmod
209(392.714084):  MDLCache: player/revo.mdl needs to be recompiled
do you know how to fix?

**Comment by UnderYouFive** [comment]
You can this- https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by BasonTaylor** [comment]
ok thanks and one last thing i hope you know how to fix is when my server
crashes it says close program a crash has happened or what ever is there a
way i can make it so it restarts by it self ? if i have to buy a server i
will but yeah

**Comment by UnderYouFive** [comment]
Add me on steam and I'll see if I can fix it. 

http://steamcommunity.com/id/underyoufive

**Comment by SticklyMan** [comment]
Glad you got the initial problem figured out. The XGUI missing data is a known bug that we're working on.

**Comment by BasonTaylor** [comment]
i figured out that it was one of my addons

**Comment by BasonTaylor** [comment]
sorry to leave you hanging UnderYouFive Helped me

**Comment by YourStalker** [comment]
What addon was it?

**Comment by BasonTaylor** [comment]
it was a chat addon atls or somthing

**Comment by YourStalker** [comment]
https://scriptfodder.com/scripts/view/231

In case someone else sees this and is wondering, it was Atlast Chat by Chewgum

**Comment by BasonTaylor** [comment]
yep

**Comment by BasonTaylor** [comment]
trouble shoot with any thing that uses Ulx
