### ISSUE TITLE
ULib hook library override: Removing the hook that is currently being called causes next hook to not be called

### ISSUE THREAD

**Issue by notcake** [Nayruden/Ulysses#395]
```lua
assert (ULib)

hook.Add ("Test", "AAA", function () print ("AAA") hook.Remove ("Test", "AAA") end)
hook.Add ("Test", "BBB", function () print ("BBB") end)

hook.Run ("Test")
```

Output
```
AAA
```

Expected Output
```
AAA
BBB
```

**Comment by Nayruden** [comment]
Very interesting! Thanks, @notcake, we'll research this and fix it ASAP if found to be true.

**Comment by yupi2** [comment]
Ignore any commits I've done that reference this issue as they either don't work for cases besides the very simple one that @notcake gave or they still are plagued with issues that arise with using an index based system.

**Comment by Nayruden** [comment]
Determined to be an actual bug.

**Comment by Nayruden** [comment]
This is fixed in the hook-update branch, which will be merged into the master over the next few weeks.
