### ISSUE TITLE
[ULX] Bug I found

### ISSUE THREAD

**Issue by Bryantdl7** [Nayruden/Ulysses#399]
1. Ragdoll yourself
2. Do a gmod_admin_cleanup
On my server this makes the person ragdolled vanish from the connected list and lose their admin rank.

**Comment by Nayruden** [comment]
Interesting, I didn't know about that function previously. It's unusual for Garry to do something quite that heavy-handed. But, since it is part of the default gmod functionality, we'll figure out a way to workaround it. Though, this is a low priority issue.

**Comment by darkjacky** [comment]
Is it the same bug as mine? https://github.com/Nayruden/Ulysses/issues/346
It sure sounds the same to me. Not that it really matters.

We disables the ragdoll function until it gets fixed.

**Comment by Bryantdl7** [comment]
Similar, I have demotions happen too.

**Comment by SticklyMan** [comment]
Yes, this is a duplicate of #346. It seems to happen any time the player entity is removed. I'll close this and add more info to the other issue.
