### ISSUE TITLE
My ULX Stuff Disappeared Bug!

### ISSUE THREAD

**Issue by BasonTaylor** [Nayruden/Ulysses#402]
My Super Admin or Admin Group Not Showing Up
          URL To PROOF! : http://gyazo.com/2904f4aa47210c052bdcd1aa89fd6e49
My Server Limits Not Showing Up!
          URL To PROOF! : http://gyazo.com/cab51c8edf471b2e68f8b0c784646785
The Server Advert Stuff Gone!
          URL To PROOF! : http://gyazo.com/0c18297acdeebbf39a88754327ab30e0
The Ban List Is Also Gone I have 10 Baned Individuals...
          URL To PROOF! : http://gyazo.com/ea5ae9618a044e557ff9c1a002a0d77b
I Tried Deleting the data Then It came Back After 1 hour Nothing is working i uninstalled it then re installed it nothing

**Comment by SticklyMan** [comment]
You are using a very outdated version of ULX. Please get the latest version by one of the following methods:

Use SVN with the two two links on our downloads page: http://ulyssesmod.net/downloads.php
-OR-
Grab the latest version as a zip by clicking "Download Zip" on our main GitHub page: https://github.com/Nayruden/Ulysses
