### ISSUE TITLE
Need a proper way to detect when menu is closed

### ISSUE THREAD

**Issue by arduinium** [Nayruden/Ulysses#405]
Hello,

There is `xgui.hookEvent( "onOpen" ...` to detect when menu is opened. I would like the same thing for when the menu is closed.

It's easy, in file xgui_client.lua, just replace near line 6:
`xgui.hook = { onProcessModules={}, onOpen={}, onClose={} }`

And add `xgui.callUpdate( "onClose" )` at the end of `xgui.hide()` near line 394.

Thanks in advance ;)

**Comment by SticklyMan** [comment]
Thanks for the suggestion!
