### ISSUE TITLE
ULX + DarkRP making some trouble with "hooks" 

### ISSUE THREAD

**Issue by Kro55f1r3** [Nayruden/Ulysses#406]
Hello guy ,

I got a problem that's occurs on my darkRP.
The DarkRP create twice "Jobs" and bug them 
HUD don't reconize the name of this job , color job is yellow (as default) and ID of the job is up to the maximum job (1 => 31 , duplicate 1 to 32 and that's for all jobs.)
When i remove ULX , that's work fine without problems
Can you give me some informations to prevent this odd bug ?

**Comment by SticklyMan** [comment]
This is most likely a conflict with running ULX and FAdmin at the same time. Please post on our support forums (or DarkRP's forums) to get help from users who have experience working with DarkRP, Jobs, and ULX.
