### ISSUE TITLE
[hook-update] Hook Errors When Using Last Used Weapon

### ISSUE THREAD

**Issue by YourStalker** [Nayruden/Ulysses#407]
When you use the last used weapon bind with the hook-update version of ULX it spits these errors:
http://pastebin.com/DnqRen1B

Everything seems to work fine though. I have only tried this on stock TTT.

**Comment by SticklyMan** [comment]
We are aware of this issue, and will hopefully get it fixed soon. It happens on sandbox as well. (It's curious that that's the only hook that's broken, though...)

Just to clarify, are you using the beta version of Garry's Mod?

**Comment by YourStalker** [comment]
No I am on the Stable branch, one more question, did you just merge the hook-update branch together with the default one? Thanks though :)

**Comment by SticklyMan** [comment]
Ah, I only thought that it occurred on the beta version of Garry's Mod. Good to know!

And nope, it was the other way around- merged some bugfixes on master into the hook-update branch :) We'll merge the hook-update into the master once we've got this bug fixed and gotten a few more testers/feedback on it.

**Comment by YourStalker** [comment]
Weird, on TTT it only happened with last weapon switch, Ill test again and get back to you

**Comment by YourStalker** [comment]
Okay so after testing it seems like it only errors serverside when you switch weapons normally but if you use last weapon switching it errors both client and server said. This is after testing on my dedicated server.

**Comment by SticklyMan** [comment]
Interesting- does it only happen in TTT? I was noticing it on sandbox on the Garry's Mod beta branch.

In fact, the error for sandbox is similar, but has a slightly different call stack:

[ERROR] gamemodes/base/entities/entities/gmod_hands.lua:53: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:310
    3. fn - gamemodes/base/entities/entities/gmod_hands.lua:53
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:107
      5. Give - [C]:-1
       6. RunClass - gamemodes/sandbox/gamemode/player_class/player_sandbox.lua:56
        7. Call - gamemodes/base/gamemode/player.lua:317
         8. PlayerSpawn - gamemodes/base/gamemode/player.lua:274
          9. unknown - gamemodes/sandbox/gamemode/init.lua:41

**Comment by YourStalker** [comment]
After testing in Sandbox the error still happened in the stable branch

**Comment by YourStalker** [comment]
Okay so after testing on Sandbox on my dedicated server I got these errors:
Clientside:
```
Error in hook OnViewModelChanged: gamemodes/base/entities/entities/gmod_hands.lua:53: bad key to string index (number expected, got string)
stack traceback:
	[C]: in function 'error'
	lua/includes/extensions/string.lua:274: in function '__index'
	gamemodes/base/entities/entities/gmod_hands.lua:53: in function 'fn'
	addons/ulib/lua/ulib/shared/hook.lua:107: in function <addons/ulib/lua/ulib/shared/hook.lua:88>
	[C]: in function '‭‬‌⁬﻿‎⁯⁮⁭'

[ERROR] 
  1. unknown - [C]:-1
```
Serverside:
```
[ERROR] gamemodes/base/entities/entities/gmod_hands.lua:53: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:274
    3. fn - gamemodes/base/entities/entities/gmod_hands.lua:53
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:107
      5. Give - [C]:-1
       6. RunClass - gamemodes/sandbox/gamemode/player_class/player_sandbox.lua:56
        7. Call - gamemodes/base/gamemode/player.lua:310
         8. PlayerSpawn - gamemodes/base/gamemode/player.lua:267
          9. unknown - gamemodes/sandbox/gamemode/init.lua:41
		  
[ERROR] gamemodes/base/entities/entities/gmod_hands.lua:53: bad key to string index (number expected, got string)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:274
    3. fn - gamemodes/base/entities/entities/gmod_hands.lua:53
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:107
```

**Comment by YourStalker** [comment]
Would like to point out that the Gmod update is supposed to be coming out Monday so worry more about that probably than the current stable version.

Also, the server side errors for TTT were the same with both last used weapon and normal weapon switch.
