### ISSUE TITLE
XGUI broken

### ISSUE THREAD

**Issue by rtlk** [Nayruden/Ulysses#408]
XGUI no longer works after the 2015.03.09 update that was just released.

**Comment by Swagrenade** [comment]
Same here. ULX commands still work, but the easy to use XGUI is gone :(

**Comment by doctorluk** [comment]
Can confirm.

**Comment by M21z** [comment]
Yea really wierd, the update must have messed it up.

All other commands are working except Xgui.

**Comment by Nayruden** [comment]
Very odd, since we tested it against the beta just a few days ago. Unfortunately, I doubt any one from the team can look at this until after we are back from work today.

**Comment by rtlk** [comment]
Just wanted to make it aware. Going to look into it myself as well. Thankfully no other issues I've seen yet

**Comment by rtlk** [comment]
From what I can tell it's not XGUI itself, but ULib actually. It is running the xgui.init() client function before the client is valid, which is causing it to run the exit with `if authedply ~= LocalPlayer() then return end` (lua/ulx/modules/cl/xgui_client.lua line 77)

Changed it to include some debugging:
```
function xgui.init( authedply )
	print("xgui init pls")
	print(authedply)
	if not authedply then authedply = LocalPlayer() end
	print(authedply)
	print(LocalPlayer())
	if authedply ~= LocalPlayer() then return end
	print("xgui init 2 pls")
```

Console output gave:
```
ULX version 3.61 loaded.
xgui init pls
Player [1][]
Player [1][]
[NULL Entity]
```

So from what I can tell when the init is ran LocalPlayer() isn't a valid player entity so it doesn't like what it sees. And authedply sees a player but not which player, as the output of `lua_run print(Player(2))` shows my player entity as usual (ie `Player[1][RTLK]`)

**Comment by rtlk** [comment]
Further tested it and it is with the ULib hook UCLAuthed on the player's load after joining/mapchange. Used `ulx adduser` to set my rank to superadmin again and it recalled UCLAuthed and xgui updated as it called the init from the hook call again and it works.

**Comment by YourStalker** [comment]
Good work! Can you make a pull request please? Curious to see what you're talking about

**Comment by rtlk** [comment]
Haven't actually fixed anything, just done debugging code to see what runs and what doesn't.

**Comment by rtlk** [comment]
Pull request #409 fixes this issue and adds a little extra redundancy that is always useful.

**Comment by SticklyMan** [comment]
Unless I'm mistaken, this bug should already be fixed with these previous two commits I made just a day ago:
bc29d70b6994d9d166dc5e7ab162e882fd596316
3e76acf21809c6192f72e706b8cbc4e4284dfbe4

Be absolutely sure that your ULX AND ULIB are up to date with the latest version here on GitHub. I will be testing myself in a moment to make sure.

**Comment by rtlk** [comment]
That did fix it. Despite having a fork of the git I still had the non-svn versions from the site installed.

**Comment by SticklyMan** [comment]
Can confirm that after today's update, XGUI still works with the fixes from 3/7/2015. No patch is needed.

Thanks for looking into it for us though, rtlk! You pretty much had the initial problem nailed down. :)

I've gone ahead and bumped the XGUI version date, so for anyone having this issue: make sure you have the latest ULX/ULib by checking that XGUI version is "v15.3.9" on the infobar at the bottom.
