### ISSUE TITLE
Access not granted to uses after gmod update

### ISSUE THREAD

**Issue by kulcris** [Nayruden/Ulysses#410]
gmod updated last night and there are issues with users still being the right rank but unable to use the ulx menu, they still have access to all the commands they should just the window will not open untill you use ulx adduser rank on them again

 the ulx who command still shows them in their right full rank 

No errors in console so far as i can tell

**Comment by TheEMP** [comment]
I don't think its an issue with permissions, but after the update the menu doesn't seem to open at all.

**Comment by kulcris** [comment]
was fixed apparently update your install

**Comment by SticklyMan** [comment]
Duplicate of #408
