### ISSUE TITLE
Still having an XGUI Issue.

### ISSUE THREAD

**Issue by SancLink** [Nayruden/Ulysses#411]
So I've updated to the latest version to attempt to fix the xgui issue I'm having and I still cannot access the menu. Any chance I could get someone to help me out?

**Comment by SticklyMan** [comment]
Did you update BOTH ULX and ULib from this GitHub repo? Does XGUI say "v15.3.9" at the bottom?

**Comment by SancLink** [comment]
I haven't updated ULib, is ULib where the groups and commands are because I don't want to loose the commands and perms that I've set up.

**Comment by SticklyMan** [comment]
Updating ULib will NOT remove users, groups, and bans- those are stored in the data folder. The fix to this issue requires an update to ULib.
