### ISSUE TITLE
Kicking yourself using !kick still causes server crash

### ISSUE THREAD

**Issue by raymond4400** [Nayruden/Ulysses#413]
I noticed that kicking yourself still is causing server crashes. Not sure why. Maybe I should just remove the !kick so they can't do it from chat for now and they have to use menu.

**Comment by SticklyMan** [comment]
Are you sure you have the latest version of both ULX and ULib? XGUI should show v15.3.9 at the bottom.

**Comment by McSniper1215** [comment]
In fact, the new gmod update broke my gui xD

Seems as if !menu doesn't work but everything else works. And yes raymond is right. Kicking yourself still fucks you up.

**Comment by SticklyMan** [comment]
The latest version of ULib and ULX fixes XGUI. Check and make sure XGUI says "v15.3.9" at the bottom. If you have the latest version and kicking yourself still causes the crash, then let me know.

**Comment by SticklyMan** [comment]
No response for a few days. I tested kicking myself and the server did not crash. Please note that sometimes other addons can trigger this issue again. Refer to #325 for more details.

**Comment by Nayruden** [comment]
I tested this on my server to with no crash.

**Comment by raymond4400** [comment]
I think the problem was I had just downloaded the release a day before you made another release LOL

I really haven't tested on the newest release because I removed the !kick from chat and force users to use menu but I will try again.
