### ISSUE TITLE
Breaks DarkRP

### ISSUE THREAD

**Issue by Maineiac** [Nayruden/Ulysses#416]
Yes I just noticed that after installing the latest GitHub, downloaded it about 5 minutes ago, the GUI problem still isn't fixed and it causes a wierd bug with DarkRP. Players don't get assigned to the citizen job, they stay Joining/Connecting with a wierd model and everyone's money is nil (not zero, nil). Just thought you'd like to know.

**Comment by SticklyMan** [comment]
Are you sure you have the latest version of both ULX and ULib? XGUI should show v15.3.9 at the bottom.

**Comment by deinemudda32** [comment]
That isnt simple true.
Works fine for me on Linux

**Comment by roastt** [comment]
This is true ULX causes bad lag and crashes I tested perfectly, I have been running DarkRP for 2 years... and I know for a fact its ULX/ULIB

**Comment by deinemudda32** [comment]
Yea its true that it cause lag, but only cause ulx saves onto one file.
But it doesnt randomy crash servers and set teams to Joining/Connecting

**Comment by roastt** [comment]
My server is in a lot of shit without ULX!

**Comment by roastt** [comment]
Please fix this fast, you don't understand how much shit im in right now trying to manage my server!

**Comment by Maineiac** [comment]
I don't know why everyone is complaining of lag, I'm not experiencing that issue. Just a random "Segmentation Fault" crash these days. The Joining/Connection issue was fixed after installing the latest version of ULX

**Comment by SticklyMan** [comment]
roastt, you are the only one complaining of these kinds of issues. If ULX and DarkRP together were causing these sorts of issues, we'd be getting a lot more complaints. There was a recent Garry's Mod update that broke some addons. Please make sure that ALL of your addons and gamemodes are up to date at their latest versions, and then try temporarily removing as many addons as you can to see if the issues go away.

They should be releasing a hotfix update to Garry's Mod in the next few days, this may help alleviate some of the crashing problems as well.

**Comment by roastt** [comment]
Ok thanks! I will come back with answers.

**Comment by roastt** [comment]
Well the gmod fix and downloading a new copy of ULX seemed to fix everything, sorry for bothering you!

**Comment by deinemudda32** [comment]
Then it was youre addons.
Facepalm.

**Comment by SticklyMan** [comment]
Glad you got it worked out, and glad that OP figured their issues out too!
