### ISSUE TITLE
Typo in ULib/lua/ulib/server/player.lua

### ISSUE THREAD

**Issue by TheRealAyCe** [Nayruden/Ulysses#417]
Line 268:
if t.invis.wep and IsValid( t.invis.web ) then

it should be wep, no?

(also, in ULX sh_defines.lua, there is the line:
ulx.release = false -- Is this the release?
which i suppose is wrong as well)

**Comment by SticklyMan** [comment]
Whoops- yeah, that should be 'wep'. I'll fix this as soon as I have a chance to test the code that should be running in that case.

As for the ulx.release = false- it looks like we just missed flipping that when we packaged the release. Not a huge deal, though.
