### ISSUE TITLE
Everything in Data folder won't load.

### ISSUE THREAD

**Issue by DutchPatrick** [Nayruden/Ulysses#418]
I got 4 servers i updated to 2015 and by suprise ULX was already updated to 3.62 lol.
But now my Data won't load.
All players are user group and they have no permissions in anything.
Configs of plugin in menu won't load also.
Only on my Sandbox it works.

**Comment by Nayruden** [comment]
Are you getting any errors in the server console?

**Comment by DutchPatrick** [comment]
Nvm. Fixed xD
