### ISSUE TITLE
Failed to include file

### ISSUE THREAD

**Issue by originalwhitestar** [Nayruden/Ulysses#420]
when I joined my server(downloaded the newest ULX & ULib) I got this error:

```
Couldn't include file 'ulib\shared\defines.lua' (File not found) (@addons/ulib/lua/ulib/cl_init.lua (line 3))

[ERROR] addons/ulib/lua/ulib/cl_init.lua:16: bad argument #2 to 'format' (number expected, got nil)
  1. format - [C]:-1
   2. unknown - addons/ulib/lua/ulib/cl_init.lua:16
    3. include - [C]:-1
     4. unknown - addons/ulib/lua/autorun/ulib_init.lua:5

```

**Comment by originalwhitestar** [comment]
NVM, ULX just failed to upload correctly, but now it fucked up TTT(worked fine before with newest gmod update)

```

[ERROR] gamemodes/terrortown/gamemode/cl_hud.lua:260: attempt to index local 'L' (a nil value)
  1. InfoPaint - gamemodes/terrortown/gamemode/cl_hud.lua:260
   2. unknown - gamemodes/terrortown/gamemode/cl_hud.lua:363
```

**Comment by SticklyMan** [comment]
There was a Garry's Mod update the other day- the TTT errors are unrelated to ULX or ULib. You'll have to get updates for all of your addons to ensure the best stability.

**Comment by originalwhitestar** [comment]
Yeah its actually this addon: https://github.com/jkralicky/Custom-ULX-Commands/issues/1 :c we sadly need some stuff it got, like copyip and stuff..
