### ISSUE TITLE
Many Servers Keeps Crashing After The Update

### ISSUE THREAD

**Issue by sentasix** [Nayruden/Ulysses#421]
Recently, after the update. 
Ulx commands got fucked up.
So me and my partner had to download the new update of ulx.
And re-make the groups.
That's ok, that was simple.
Now.. when people joins. 12-20 ( we have 52slots ), the server keeps crashing.
This happens everytime, someone tried to build with toolgun, or joins.
And this happened AFTER the update. 
Our server was fine before the update, and got fucked up after the update.
So here i am today, trying to fix the issues that may cause this.
And needs help from the people who did this update.
So.. can anyone help out? 
There is not just us that had this problem.

Thanks For Reading.

**Comment by Nayruden** [comment]
Unless you can make a case otherwise, we're forced to assume that your problems are coming from the GMod update on Monday. ULX is working fine for many people. "It crashes" is not enough for us to take any kind of action.

**Comment by sentasix** [comment]
My apologize for not being detailed. 
Yes, that is from the update on Monday.
Been testing in-game on the server for quite a long time, and the only answer i got. Is the toolgun.
Mabye I need to just reinstall WireMod mabye? It may cause crash, since the update.

**Comment by sentasix** [comment]
My apologize for not being detailed.
Im trying to, but its so hard to explain.
When i have no idea, why it crashes.
Been testing out, checking. What may cause this.
And the only answer i got is the toolgun.
Mabye the WireMod needs updating? Delete it and reinstall it?

**Comment by sentasix** [comment]
My Apologize For Not Being So Detailed.
Yes it came from the GMod update Monday.
It is so hard to explain, because I have no idea to be honest.
That what may cause the server to crash, the only thing i do know is that it happened after the update.
Been testing out, checking what may cause this.
And the only answer I got is the toolgun.
So mabye WireMod that needs to be updated? Deleted, then reinstalled?
I know its hard to help out, when you don't know where to start.
But this is all i got.

**Comment by Nayruden** [comment]
I'm sorry, you'd be better off asking at FP.
