### ISSUE TITLE
ULX Not adding/keeping ranks after gmod update.

### ISSUE THREAD

**Issue by Samg381** [Nayruden/Ulysses#422]
As of the recent gmod update, my server is no longer setting people as their ranks.
The users.txt / groups.txt / bans.txt files are all intact however all of my administrators, VIP's, Donators, etc. Have lost their privileges. I updated ULX to the most recent version and the data in the /data folder remains untouched. This is very urgent and is preventing me from running my server.

**Comment by Nayruden** [comment]
Make sure your OS's write permissions are enabled to the data folder and
files.

**Comment by YourStalker** [comment]
Ran into this issue a few days ago. This will help you.
http://facepunch.com/showthread.php?t=1455047&highlight=

**Comment by Samg381** [comment]
Appears to be fixed. Thank you.
Now to move onto the litany of other errors in other addons -_-
