### ISSUE TITLE
AdvDupe2 + URS + ULX

### ISSUE THREAD

**Issue by Xer0n** [Nayruden/Ulysses#423]
Players are unable to use AdvDupe2 on two of my build servers, and the only error to report is below.

[AdvDupe2Notify]	lua/ulx/modules/urs_server.lua:114: attempt to call global 'URSCheck' (a nil value)

**Comment by arduinium** [comment]
I've reported the issue on the [https://github.com/Aaron113/URS/issues/18]URS Github, it's not related to ULX or AdvDupe2
