### ISSUE TITLE
Simply Multi-Servers sync compatibility

### ISSUE THREAD

**Issue by flydvorkin** [Nayruden/Ulysses#425]
Many peoples have a problem related to sync with 2 or more servers (USERS, GROUPS and BANs).

Very simply to create hard symlinks for users.txt, groups.txt, bans.txt across servers, but here we have a problem: ulx load this files initially when start and do not refresh data from theese files until working (working with loaded data). If at one server makes changes - files are rewritten, but other servers ignore changes in files (because not refreshing data). As result one server may to ignore and delete changes written by other servers.

I think what need regular (each 5 minute) refresh data from files. Also re-load data required before operations:
reload bans.txt before ban/unban
reload users.txt before add or remove users from groups
reload groups.txt before change groups settings
But i understand what with multiple servers script sometimes may conflict to open file for read/write. Because possible make some retries to open file until is unlocked. (Time to open file for read/write is very short).

Please, add this reload option to ULX

**Comment by Nayruden** [comment]
We will not support this.

While technically possible to share data between multiple processes this way, it is a terrible, terrible idea. If you want to share information between servers, use SQL.

**Comment by flydvorkin** [comment]
It is nice recomendation to use SQL, especially when consider the one fact that this tool does not exist.

**Comment by flydvorkin** [comment]
If you release sql version of ulib, then this advice would be helpful. In the absence of that version - would helpful any implementation of this idea.

**Comment by Nayruden** [comment]
I'm sympathetic but not apologetic. There are plenty of third party SQL-type ULib addons.

**Comment by Neosinos** [comment]
Globalban for example, even though it's not really working good on servers
with a big playerbase.

Am Dienstag, 17. März 2015 schrieb Brett Smith :

**Comment by 00875** [comment]
You can try https://github.com/00875/Ulysses/tree/sql
