### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by deinemudda32** [Nayruden/Ulysses#426]
[ERROR] addons/ulx/lua/ulx/modules/sh/fun.lua:628: attempt to index field 'physgunned_by' (a nil value)
  1. fn - addons/ulx/lua/ulx/modules/sh/fun.lua:628
   2. unknown - addons/ulx/lua/ulib/shared/hook.lua:184

Do I have to explain :(?

**Comment by Nayruden** [comment]
Some additional context would have been helpful in figuring out if there was an underlying issue, but regardless, that commit will fix the error from occurring. :)
