### ISSUE TITLE
Slaynr doesn't make the person innocent

### ISSUE THREAD

**Issue by RedVisionx** [Nayruden/Ulysses#429]
Before slaynr you're assigned to a role and you're no longer assigned to innocent. You may now be slain as a traitor or detective. You should make it like it was (force role innocent before slaynr).

**Comment by SticklyMan** [comment]
slaynr is custom ULX command that we do not package with ULX. You'll need to direct your complaint to the author of the slaynr command.

**Comment by Decicus** [comment]
Slaynr is most likely part of this command package, so I recommend posting there instead: http://forums.ulyssesmod.net/index.php?topic=7437
