### ISSUE TITLE
Adding Admin Group's

### ISSUE THREAD

**Issue by BasonTaylor** [Nayruden/Ulysses#430]
Ok this is the one problem i keep running in to when adding New Admin Groups Such as Senior Admin and Chair man and owner When trying to no clip Via "V" it does nothing but when typing "!noclip" it works But every thing els works fine.

**Comment by Nayruden** [comment]
This area is for bug reports, not help and support.

**Comment by BasonTaylor** [comment]
i thought it was a bug jezz
why are people jerks

**Comment by SubjectAlpha** [comment]
That's because you didn't add FAdmin groups in DarkRP. Its not a ULX issue.

**Comment by BasonTaylor** [comment]
thank you
