### ISSUE TITLE
Random Queue Error

### ISSUE THREAD

**Issue by YourStalker** [Nayruden/Ulysses#431]
I don't think this really did anything but I saw this in my serverside console:
ULib queue error: addons/ulx/lua/ulx/modules/sh/fun.lua:679: Tried to use a NULL entity!

No clue why or if it really did anything, just putting it up here.

**Comment by P4sca1** [comment]
I encountered this issue too. Sometimes it is crashing the server. It seems that clients are loosing ranks becuase of that. 
This error usually comes up, when somebody is using the ragdoll command. 
Please fix!

**Comment by YourStalker** [comment]
You are probably having a different issue then. This is not  crashing my server or wiping player ranks at all. It is probably another addon you have causing it or if you modified ULX directly which you want to avoid.

**Comment by SticklyMan** [comment]
I believe that the cause was an Admin running map cleanup while a player is ragdolled.
f7634c87875f0b2ea590b71706002f4352af0ef6 Should fix the problem! :)
