### ISSUE TITLE
Potential issue with votemaps and XGUI.

### ISSUE THREAD

**Issue by SticklyMan** [Nayruden/Ulysses#433]
This has seemingly been reported twice:
http://forums.ulyssesmod.net/index.php/topic,8306.0.html
http://forums.ulyssesmod.net/index.php/topic,8319.0.html

I want to double check that the hook priority change didn't affect XGUI in relation to how it handles votemaps.

**Comment by 00875** [comment]
I have this too. When i change votemap list what are HUGE sizes, it would not save or it will be recreated with all/or no one map listed.

**Comment by Neosinos** [comment]
Confirm

Am Donnerstag, 14. Mai 2015 schrieb RoboDerpy :
