### ISSUE TITLE
Bans Not Appering

### ISSUE THREAD

**Issue by BasonTaylor** [Nayruden/Ulysses#434]
My Bans On My Server Are Not Being Loged on the Bans Tab And I canot unban them and when they try to join they canot

**Comment by SubjectAlpha** [comment]
Would you happen to be using the ULX Global Bans module?

**Comment by BasonTaylor** [comment]
whats that

**Comment by SubjectAlpha** [comment]
Never mind then. With that module for ULX it doesn't update.

**Comment by BasonTaylor** [comment]
my bans tab in the ulx !menu

**Comment by SticklyMan** [comment]
Unable to reproduce. Please make sure your version of ULX and ULib are up to date, and that you are not using a modified banning system for SQL or Sourcebans support. You may also have a conflicting addon or gamemode which may be contributing to the problem.

For further help and assistance, please create a thread on our forums at http://forums.ulyssesmod.net
