### ISSUE TITLE
ULX wont keep rank 

### ISSUE THREAD

**Issue by LobzGaming** [Nayruden/Ulysses#435]
Hello :) 

I'm admin on a darkrp server. 
We have a few groups. VIP, Admin, Headadmin, Owner and User. 
When i(and the other users/admins) rejoin the server it makes me/them "User" again. 
Can you help. It's very annoying.

**Comment by SticklyMan** [comment]
We've recently fixed a bug regarding this- are you running the latest development version from our GitHub repository here? XGUI should say "v15.3.18".

**Comment by LobzGaming** [comment]
I'm not that good to ulx. But if i type "ulx help" it says at the bottom. 

ULX version: <SVN> revision 297

**Comment by YourStalker** [comment]
What OS are you on?

**Comment by LobzGaming** [comment]
Windows 7

**Comment by SticklyMan** [comment]
How frequently is this issue occurring for you? Is it happening for just you or other admins on the server?

**Comment by LobzGaming** [comment]
its for ALL on the server. Not just me.

**Comment by YourStalker** [comment]
I assume you're running it from your PC? Check the /garrysmid/data/lib/groups file, does it have you in there as superadmin (Or whatever rank you should be)? If it doesn't then try running your server as admin.

**Comment by SticklyMan** [comment]
Could we hop on your server later today (in 5 or 6 hours, once we're not at work) and take a peek? We haven't been able to properly replicate this issue, and it would be very helpful for us to be able to see what exactly is going on.

Add me on Steam, and I'll get in touch with you for more details. http://steamcommunity.com/id/Stickly_Man

**Comment by LobzGaming** [comment]
Nope. The owner has got a host. So not running on my pc :)

**Comment by LobzGaming** [comment]
Sticklyman. The thing is that when the users rejoin/lose connection and join again they loses their rank. For example. I get VIP and then i rejoin because I got to eat. And then i loses VIP.

**Comment by SticklyMan** [comment]
Yes- the issue is the same as #302, which we thought we had a fix for. We want to join the server to see if we can learn anything new about it. Megiddo will likely need some permissions temporarily for testing, so we may need help from your server owner as well.

**Comment by LobzGaming** [comment]
You can join as much as u want. Just add " http://steamcommunity.com/id/ItsDeltalol "  And " " http://steamcommunity.com/id/LobzGaming/ "

**Comment by MrUnknownGamer** [comment]
This is happening with me too

**Comment by MrUnknownGamer** [comment]
NVM Updated fixed it. Are you SURE you updated?

**Comment by LobzGaming** [comment]
Yeah, The reason for this is bacause it is a beta version. Thank you guys for the help
