### ISSUE TITLE
I am missing groups section from my menu.

### ISSUE THREAD

**Issue by Maturees** [Nayruden/Ulysses#438]
I cant change things in groups and its pissing me off. Havent found a fix for it. This is how my !menu looks like: http://puu.sh/gT4rG/95e464c179.jpg  
All help appreciated!

Matu

**Comment by MrUnknownGamer** [comment]
this happened to me too along time ago when doing a job on scriptfodder. I was puzzled. Forums didn't do much help.

**Comment by SticklyMan** [comment]
Sorry for the delay- is this still an issue?

Can you verify that your group has access to "xgui managegroups"? The tab won't show up if you don't have access to that. You can add it back by using this command: (replace 'superadmin' with your current group)
ulx groupallow superadmin "xgui managegroups"

**Comment by SticklyMan** [comment]
No response for a few weeks- I'm assuming this is no longer an issue. Feel free to visit us at http://forums.ulyssesmod.net/ if this pops up again, and we can help you further from there.
