### ISSUE TITLE
Lua error when joining server: [ERROR] Unauthed player

### ISSUE THREAD

**Issue by KoriSkylight** [Nayruden/Ulysses#439]
Everytime i join my server it gives me this error and also to all players that joins too:

[ERROR] Unauthed player
  1. query - [C]:-1
   2. adminCheck - addons/uclip/lua/autorun/sh_uclip.lua:29
    3. fn - addons/uclip/lua/autorun/sh_uclip.lua:198
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

**Comment by pmx625** [comment]
That happens aswell when I join my server. It also happens to other players.

**Comment by KoriSkylight** [comment]
The error also makes so i can't acces the !menu or fly with WAC Aircraft

**Comment by pmx625** [comment]
Yeah I can't access !menu either. But I am able to use WAC Aircraft.

**Comment by Nayruden** [comment]
Are you still getting this error?

**Comment by pmx625** [comment]
Not for the moment. I updated my garry's mod server and menu is showing up again and ulx is running well.

**Comment by Nayruden** [comment]
No further feedback, no further complaints. Assuming the issue has resolved itself in Gmod updates.
