### ISSUE TITLE
Odd Rank Problem

### ISSUE THREAD

**Issue by tonnuminat** [Nayruden/Ulysses#440]
I got the problem with the ranks but a little bit different(I run TTT). What I noticed:

-When players join the rank chattags won't work but they still have their permissions (admins too) and still have their rank when i look into the "Groups" tab. 
-Another odd thing is after every server restart utime resets the player time(shown in the UI). But the sv.db entrys are still increasing like intended.
-People are shown as "Spectator" immediatly when they die without someone identifying them. The TTT help page says that means detective mode isn't enalbed. But i have detectives and it always worked until now and i didn't change anything.(might not be an ulx problem)

I heard large users.txt and sv.db files can cause the bug.
My users.txt is 67kB / 7700 rows. Resetting it didn't help.
My sv.db is 42mB bc of a custom damagelog we use. Dropping the damagelog tables reduced it to 2,2 mB but didnt' fix the problem either.

These things just appeared out of nowhere today. And like I said I didn't change anything the last weeks.

**Comment by Nayruden** [comment]
UTime issue reported in #444, other issues do not seem to be related to ULX/UTime (if they have the permission, then ULib is working as intended, chattags is something else).
