### ISSUE TITLE
users.txt Overwrite

### ISSUE THREAD

**Issue by Neosinos** [Nayruden/Ulysses#441]
Maybe this is a duplicate, but I didnt find anything in my quick search.

When starting the Server with a big users.txt (30k+), it will not load this Text File. It will create a users_backup.txt and place the entrys there, then start with a blank users.txt

Anyone know if this is a global Issue or related to maybe some kind of syntax error?

Edit: Defo no Syntax Error. Just gone through the whole Users List, everything is correct.

**Comment by Nayruden** [comment]
If it creates a backup, it means there's a syntax error in your file. Read
the console to find out what and where.

**Comment by Neosinos** [comment]
There is no Output in the Console. its as soon as ULX loads. I've checked the file twice, even removed uncommon letters from Playernames. I didnt find anything.

**Comment by Nayruden** [comment]
A backup is never created except in the case of a syntax error

**Comment by Neosinos** [comment]
I guessed so. Even though I havent found any. Should it print anything in Console? eg the Line where the Error occured?

**Comment by Nayruden** [comment]
It will always at least print "Users file was not formatted correctly. Attempting to fix and backing up original". If it can pinpoint the problem further than that, that message will come next.
