### ISSUE TITLE
UTime won't store times after server reset.

### ISSUE THREAD

**Issue by GGG-KILLER** [Nayruden/Ulysses#444]
Every time the server gets reset, everyone's time gets reset too, everyone's time is the same and the Session time and Total time are shown as the same.

**Comment by Nayruden** [comment]
No one else seems to be having this issue, assuming something is going on with your local DB. For more help, go to our forums->help and support.

**Comment by Nayruden** [comment]
Fixed via @GGG-KILLER in 21f1874048b0bf3d85105182e6b39eea10553b63
