### ISSUE TITLE
hook.Remove completely broken.

### ISSUE THREAD

**Issue by FPtje** [Nayruden/Ulysses#445]
```
] lua_run show(hook.GetTable().PlayerSay)

table: 0x290b24e0
...
nilnil╠ ULXMeCheck                   = function: 0x29145a60	-- [addons/ulx/lua/ulx/modules/sh/chat.lua]: 269-294
...


] lua_run hook.Remove("PlayerSay", "ULXMeCheck")


] lua_run show(hook.GetTable().PlayerSay)
...
nilnil╠ ULXMeCheck                   = function: 0x29145a60	-- [addons/ulx/lua/ulx/modules/sh/chat.lua]: 269-294
...
```

I can't remove any of the hooks in PlayerSay. In fact I **can't remove any hooks at all.**

**This is an emergency bug. You're breaking loads of scripts with this error. Fix this ASAP**
https://github.com/FPtje/DarkRP/issues/1868
http://forum.darkrp.com/threads/me-ulx-darkrp.4752/

**Comment by SticklyMan** [comment]
Looks to be a missed statement removing the hook from BackwardsHooks. I'm committing a quick fix to patch the issue for now, but I'll have Megiddo verify to be sure.

Either way, it still looked like the hook should have been "removed" properly, it was just showing that the hook was still there:
```
lua_run hook.Add("ASDF", "asdf", function() print("asdf") end)
> hook.Add("ASDF", "asdf", function() print("asdf") end)...

lua_run hook.Call("ASDF")
> hook.Call("ASDF")...
asdf


lua_run hook.Remove("ASDF", "asdf")
> hook.Remove("ASDF", "asdf")...

lua_run hook.Call("ASDF")
> hook.Call("ASDF")...

lua_run PrintTable(hook.GetTable().ASDF)
> PrintTable(hook.GetTable().ASDF)...
asdf    =       function: 0x1c109b88
```

**Comment by FPtje** [comment]
Thanks for the quick fix!

**Comment by SticklyMan** [comment]
You're lucky I was awake at this odd hour :P

**Comment by Nayruden** [comment]
@FPtje, I just wanted to double check with you -- hooks were being removed, just not reflected in the debug info (the backwards-compatible hook table). Was this consistent with the behavior you observed? I'm just a little confused why you marked this as an emergency.

**Comment by FPtje** [comment]
They really didn't remove, see the two links in op.

**Comment by Nayruden** [comment]
We didn't change any functionality regarding hook removal.

**Comment by FPtje** [comment]
In hindsight it might be because of the way DarkRP handles PlayerSay
specifically.
