### ISSUE TITLE
Add MySQL Support [enhancement]

### ISSUE THREAD

**Issue by 00875** [Nayruden/Ulysses#446]
If it is possible, please add MySQL support. This will be more faster (and secure by InnoDB), because MySQL parse tables very fast (performance improve). Also there is need table prefix option.

ULX (and Ulib) will create few (or more) tables to store data flexibly.
For example:
ulib_users - will store uniqueID(what internally will be used by Ulib and ULX),SteamID, and rank(Name)
ulib_users_access - will store user privilegies (uniqueID,command,access(false or true)). In each table line only one privilege will be stored.
ulib_bans - will store bans (SteamID_banned,user_name(NULL if not persist),admin_name(NULL if by console),expires(NULL if permanent),reason(NULL if not persist))

ulx_adverts - will store adverts (uniqueID,time,text(TEXT),red,green,blue,center(false or true),time_on_screen(NULL if not on center))

Optional:
ulx_config - config.txt 
ulib_groups - I think it's can't be released
ulib_options - misc_registred.txt
votemaps - Not needed

And for SQL - You can simply learn it by using phpMyAdmin http://www.phpmyadmin.net/home_page/index.php (it has human interface and there is function to show SQL queries)

**Comment by Sjokomelk** [comment]
+1

Den lørdag 4. april 2015 skrev 00875 <notifications@github.com> følgende:

**Comment by YourStalker** [comment]
Guys, stop asking. They made it clear that it's not going to happen.

Maybe in ulx 4 tho...???? :D

**Comment by rautamiekka** [comment]
I doubt it'll ever happen, YourStalker, if someone doesn't code it for them or pay them 1kUSD (likely not even then). It's alot the same as with Micro$oft.

**Comment by Decicus** [comment]
MySQL is unlikely, since it's not supported by Garry's Mod without an external module. However, SQLite should be possible because that is supported by default and this is something they have discussed as far as I know.

**Comment by 00875** [comment]
SQLite is always crashes. I don't use standart UTime because DB is crashes very frequently. And my DarkRP server is using MySQL. PointShop DB in SQLite crashing more frequently than UTime. And MySQL are very easy to explore and administrate.

**Comment by Decicus** [comment]
I'm not saying MySQL is hard to use, especially not with the right tools, but my point still stands about Garry's Mod not supporting it by default.

**Comment by MrUnknownGamer** [comment]
A lot of people dis agree. But if someone remebers, there was ULX MySQL on coderhire thats shut down (Should hopefully open soon) and it was $5. Maybe we can make MySQL for ULX since coderhire shut down. Syncs ranks across servers. I agree with this. 
+1 Itll be hard work but its worth it

**Comment by Nayruden** [comment]
Related: #15, #425, and #397.

We have no plans to support any form of SQL other than possibly SQLite at this time. However, in the next major version of ULX we will likely integrate some form of SQL (no ETA on this, sorry).

**Comment by Nayruden** [comment]
@00875, I've never heard of Gmod-SQLite being buggy, can you point me to some references on that? That will be very important for some future ULX decisions.

**Comment by 00875** [comment]
When server starts, it's opens a "SQLite pool". When server crashes (or something) this pool closes abnormally. If something is being do with db, it would corrupt. Server will contine working with db, but corrupt data will be ignored (and thath why PointShop not work, if server crashes) against being removed. There are many arguments for using MySQL over SQL. And, you know what server on 'exit' crashes too.
![2015-04-07_18-29_roboderpy ubuntu](https://cloud.githubusercontent.com/assets/6339511/7022258/02eb10ee-dd54-11e4-8eee-5dfbefdfd9be.jpg)

**Comment by Nayruden** [comment]
Huh, interesting. Thanks for sharing that information. :)

**Comment by 00875** [comment]
https://github.com/00875/Ulysses/tree/sql
