### ISSUE TITLE
Support for NextBot players

### ISSUE THREAD

**Issue by BurgerLUA** [Nayruden/Ulysses#447]
A nextbot created using http://wiki.garrysmod.com/page/player/CreateNextBot doesn't seem to be supported. A number of errors pop up when the nextbot is doing various things

SPAWNING AFTER THE FIRST TIME

[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
  1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:105
    3. Spawn - [C]:-1
     4. unknown - addons/fakeplayer/lua/autorun/server/sv_fakeplayer.lua:132

[UPS ERROR] Ownership table is not setup for a ply in onEntRemoved! Could be a bad UPS addon installed or bad initialization?   Please report this error to ulyssesmod.net with information on how you got it.

--------

LEAVING THE SERVER:

[ERROR] lua/includes/extensions/table.lua:161: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Count - lua/includes/extensions/table.lua:161
    3. fn - addons/ups/lua/ups/modules/player_leave.lua:84
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

[UPS ERROR] Ownership table is not setup for a ply in onEntRemoved! Could be a bad UPS addon installed or bad initialization?   Please report this error to ulyssesmod.net with information on how you got it.

--------

**Comment by Nayruden** [comment]
Absolutely will look into this, thanks for notifying us.
