### ISSUE TITLE
ULib's hooks.lua breaks Pointshop

### ISSUE THREAD

**Issue by TomatoCo** [Nayruden/Ulysses#449]
Uninstalling ULib and ULX prevents Pointshop from breaking. When they are installed, they cause the following error to be created.

```
[ERROR] addons/pointshop/lua/pointshop/sv_player_extension.lua:283: attempt to index field 'PS_Items' (a nil value)
1. PS_HasItem - addons/pointshop/lua/pointshop/sv_player_extension.lua:283
2. PS_hasItemEquipped - addons/pointshop/lua/pointshop/sv_player_extension.lua:287
3. fn - addons/pointshop/lua/pointshop/sh_init.lua:145
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:108
```

A good resolution would be either to fix this bug such that hooks correctly behave as they do before ULib's interference, or to expose the original hook functions so that hooks that require them may use them.

**Comment by Nayruden** [comment]
Just because ULib is mentioned in the stack trace doesn't mean that it has anything to do with the error. You'd receive the same error (sans ULib path) no matter what.

**Comment by TomatoCo** [comment]
Removing ULib prevents the error from occuring. When ULib is not installed on the server, Pointshop works correctly. When ULib is installed on the server, it spams that error into console.

Please investigate this.

**Comment by MrUnknownGamer** [comment]
Im getting this too and its only when Ulib is installed. It also causes people to be the grey guys and the round not to start

**Comment by yupi2** [comment]
@MrUnknownGamer @TomatoCo I had the same issue with the PointShop before and it was caused by the PS not validating (that's it's not nil) the player data files in /data/pointshop/. Try sorting the folder by size and deleting any of the files that are empty or whose size is less than the average file size (20 bytes was average for me I believe).

**Comment by MrUnknownGamer** [comment]
My storing is by MySQL. Not pdata though @yupi2

**Comment by Nayruden** [comment]
Unable to replicate your issue, @TomatoCo.

**Comment by Nayruden** [comment]
@TomatoCo, are you running Linux?


>

**Comment by SticklyMan** [comment]
FYI: Further investigation of this issue should be continued on our forums at the following thread:
http://forums.ulyssesmod.net/index.php/topic,8426.0.html
