### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by Suspect** [Nayruden/Ulysses#45]
If you edit a lua file in the FTP and save it the server would automatically refresh, the problem with ULX is that after this refresh happens the chat commands stop working like !menu, etc.

ULX continues to work but you have to use the console like "ulx menu" and etc.

**Comment by SticklyMan** [comment]
This (among with a lot of issues involving autorefresh) has been fixed in the latest batch of updates. ULX/ULib should be much more autorefresh friendly now!
