### ISSUE TITLE
Ban error

### ISSUE THREAD

**Issue by BCBEST** [Nayruden/Ulysses#455]
XGUI queue error: addons/ulx/lua/ulx/xgui/bans.lua:413: attempt to index local 'baninfo' (a number value)

I get that every time someone joins the server.

**Comment by MStruntze** [comment]
Do you have any addons related to ulx that could be modifying ban info?
When did you last update ulx?

**Comment by Nayruden** [comment]
You seem to be using an old version, line 413 does not contain 'baninfo'.

**Comment by Nayruden** [comment]
In fact, bans.lua hasn't been updated in eight months -- you are using a REALLY old version.

**Comment by BCBEST** [comment]
I am up to date on all files.
