### ISSUE TITLE
Setting default scale doesnt set the camera/weapon to the appropriate scale height

### ISSUE THREAD

**Issue by fatalberba** [Nayruden/Ulysses#458]
So on the DarkRP server I play on, we have a job called Chloe. The owner set the default scale size to .85 instead of the default 1. The playermodel spawns in correctly, however the camera and the weapons are still viewing/shooting from the default height. This can be fixed by manually rescaling the player with the !scale command, however its extremely annoying to do so. Is there any way a script could be written, or a patch to the mod could be made that solves this issue?

**Comment by Nayruden** [comment]
Not sure how this has anything to do with Ulysses.
