### ISSUE TITLE
Loss of rank admin ulx

### ISSUE THREAD

**Issue by Somedeos** [Nayruden/Ulysses#461]
Hi,
I have a huge problem after disconnecting a vip player or a server reboot players and admin lose their rank, and I find no solution.

On my said to contact you on steam but no answer , here is my steam : Somedeos Hypérion

**Comment by Nayruden** [comment]
Are you using DarkRP/FAdmin?

**Comment by SticklyMan** [comment]
Closing for no response in quite a while. If this is still an issue, please post a thread on our forums at http://forums.ulyssesmod.net , and we will provide additional help there.
