### ISSUE TITLE
players losing their ranks 

### ISSUE THREAD

**Issue by streetkilln** [Nayruden/Ulysses#463]
iv recently encountered this issue where some players would loose their rank after a server rejoin.

i have the newest version of ulx and i have darkrp. i have never had this issue it recently started to happen.

**Comment by zpetty33** [comment]
Did you install anything recently? This sounds like a conflict in addons. Particularly FAdmin which comes with DarkRP by default.

The only thing I can suggest is that you make sure your server has permission to read and write to your data folder.

**Comment by streetkilln** [comment]
dont use fadmin, the only thing i added recently is https://scriptfodder.com/scripts/view/868/comments/ 
i put a comment on this script saying it might be conflicting with ulx, its supposed to logs ulx commands, im waiting for his reply,

**Comment by zpetty33** [comment]
Try removing it temporarily to see if the problem stops.

**Comment by streetkilln** [comment]
its kind of tricky, i mean ranks dont get removed right away some people get rank loss here and thier, me my self lost it once today and couple my staff members aswell lost their ranks. it just happens out of the blue.

**Comment by zpetty33** [comment]
ULX loads ranks into memory and then dumps the entire thing to a file when it saves.
If there were something wrong with ULX, you'd lose all your ranks, not just one or two here and there.

I would love to help you, but every time this has come up, it's always been a conflicting mod. You're sure you're not running FAdmin? You're running DarkRP. Did you remove FAdmin?

**Comment by 00875** [comment]
This is DarkRP problem. Delete in https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/fadmin/fadmin/access/sv_init.lua
Next hook:
hook.Add("PlayerInitialSpawn", "FAdmin_SetAccess", function(ply)
	MySQLite.queryValue("SELECT groupname FROM FAdmin_PlayerGroup WHERE steamid = " .. MySQLite.SQLStr(ply:SteamID())..";", function(Group)
		if not Group then return end
		ply:SetUserGroup(Group)

		if FAdmin.Access.Groups[Group] then
			ply:FAdmin_SetGlobal("FAdmin_admin", FAdmin.Access.Groups[Group].ADMIN_ACCESS)
		end
	end)
	FAdmin.Access.SendGroups(ply)
end)

**Comment by Neosinos** [comment]
I dont think this is a solution at all, you tell people to edit Core Files?
Fml...
Song will be up this weekend @FPtje

Am Donnerstag, 14. Mai 2015 schrieb RoboDerpy :

**Comment by 00875** [comment]
I solved this problem on my DarkRP server by deleting this lines.

**Comment by FPtje** [comment]
You break FAdmin with that. Good fucking job. @Neosinos thanks for the help, and please post it here as soon as it's up.

**Comment by 00875** [comment]
@FPtje Why you think what i broke FAdmin? All works perfect, after that edit. If i disable FAdmin ranks too doesn't resets. Only one admin ranking system at time!

**Comment by FPtje** [comment]
You literally removes the code that fetches the ranks and assigns them. How
about instead you set the ranks in FAdmin? Until CAMI exists, that's the
perfect solution, and you don't have to edit the god damn DarkRP core
files.

Ranks will save if you set them with FAdmin.

**Comment by 00875** [comment]
FAdmin saves admin ranks
![2015-05-14_21-10_derpco ddns net](https://cloud.githubusercontent.com/assets/6339511/7633326/a3fe225a-fa7d-11e4-845e-ec7daebf9290.jpg)
And changing ranks in FAdmin are successfully.
But after player rejoin he lose their rank, BUT in FAdmin DB hes is listed as Admin AND in ULX is listed as Admin. After he leave, he would lose their rank in FAdmin and ULX. But if i change map during their ghosty 'rank lose', rank will come back. Anomaly?

**Comment by FPtje** [comment]
http://corefiles.darkrp.eu/

**Comment by Nayruden** [comment]
Not dealing with FAdmin<->ULX issues until we've had some further discussions on a way ahead with @FPtje.
