### ISSUE TITLE
Add type like ULib.cmds.FloatArg

### ISSUE THREAD

**Issue by 00875** [Nayruden/Ulysses#469]
Because using ULib.cmds.StringArg and then using tonumber() is so booring.
NumArg accepts only number, not float

**Comment by Nayruden** [comment]
Lua's numbers are floating point already. If you want to make it an integer, you can set use the cmds.round flag.

**Comment by 00875** [comment]
Floating on serverside, but no the clientside. 
music_volume:addParam{ type=ULib.cmds.NumArg,min=0,max=1,default=0.5, hint="Volume (0-1)" }
In console ulx musicvolume 0.3 will be successful, but in XGUI it is restricted between 0 and 1
![2015-06-02_08-52_garry s mod](https://cloud.githubusercontent.com/assets/6339511/7927036/d971426a-0904-11e5-975a-6b3230493d3b.jpg)
![2015-06-02_08-52_garry s mod 2](https://cloud.githubusercontent.com/assets/6339511/7927037/dd8fb6ce-0904-11e5-8792-5186229f9836.jpg)
![2015-06-02_08-53_garry s mod](https://cloud.githubusercontent.com/assets/6339511/7927038/e2c3077c-0904-11e5-9531-19a78067b43e.jpg)

**Comment by Nayruden** [comment]
I don't know much about XGUI design choices. :)

@SticklyMan, care to comment?

**Comment by SticklyMan** [comment]
XGUI's cmds tab currently treats all NumArgs as Integers. Whoops. :P 

Thanks to Nayruden's heads up though, I was able to implement a fix to XGUI where if the max - min value was less than 10 (or 5), then it would add 1 or 2 decimal places, IF the argument was not flagged with cmds.round.

Try 31f292516f7d6b379cdcaaedc5e6921ff58db306 and see if it works for you! :)

**Comment by 00875** [comment]
All works now! Thanks!
![2015-06-02_11-39_garry s mod](https://cloud.githubusercontent.com/assets/6339511/7928535/0c66183c-091c-11e5-93c2-13e958c68611.jpg)
