### ISSUE TITLE
Rename SilentSlay to SwiftSlay?

### ISSUE THREAD

**Issue by brandonsturgeon** [Nayruden/Ulysses#472]
Currently `ulx sslay` "silently" slays people. I understand what it's meant for, but it's definitely not a silent command seeing as how everyone can see that the command was run. I suggest we rename it to SwiftlySlay, so that it's clear that it's not meant to be a "silent" command, or make the command not appear at all in chat.

I don't know what the original idea behind Silent Slay was, so there might be a better way to make the command more clear. But I can't tell you how many times over the years I've had users tell me that my "ulx was broken" because they could see the silent slay command.

**Comment by darkjacky** [comment]
http://wiki.garrysmod.com/page/Player/KillSilent
they removed the needed information. Silent Slay will basically remove the player. they will die without ragdoll and without sound.( leaving no trace )

**Comment by brandonsturgeon** [comment]
Right, I'm familiar with the way the command should work, I'm just saying the naming could be a bit confusing.

**Comment by SticklyMan** [comment]
This is likely not something we'll implement, but you can feel free to rename the command yourself by editing this line in your ULX installation:

https://github.com/Nayruden/Ulysses/blob/master/ulx/lua/ulx/modules/sh/fun.lua#L122

If you don't want to have to make that edit every time you apply a ULX update, then feel free to make a copy of the sslay command outside of the ulx folder, and modify it to suit your needs.
