### ISSUE TITLE
ULX Log spam due to chat causing a crash

### ISSUE THREAD

**Issue by SticklyMan** [Nayruden/Ulysses#473]
This issue has been reported a couple of times, so it is something we should look into. So far, both reports mention TTT, and I'm curious if changes/bugs in the latest TTT are causing it. (Or, perhaps it's a poorly coded addon)

See:
http://facepunch.com/showthread.php?t=1469670
http://forums.ulyssesmod.net/index.php/topic,8654.0.html

**Comment by deinemudda32** [comment]
Running TTT and I dont get this bug.
Newest version from github

**Comment by Drathothic** [comment]
I'm running the same thing as deinemudda32, and I also do not get any bugs. I also have the latest updates from the gmod github.

**Comment by iSnipeu** [comment]
Not related to ulx, this was caused by a bad commit to TTT. You can see the discussion about it on the revert commit. https://github.com/garrynewman/garrysmod/commit/3826e0869128f8164fcf6b46449780d1ca6f7fd1

**Comment by SticklyMan** [comment]
Thanks for the info and help, everyone!
