### ISSUE TITLE
Utime and Pointshop won't save data

### ISSUE THREAD

**Issue by DutchPatrick** [Nayruden/Ulysses#474]
I got Utime and Pointshop plugin but the time doesnt save also the same problem with Pointshop, already tried to reinstall ulib/ulx, still the same.

**Comment by Nayruden** [comment]
Are you using the latest UTime?

**Comment by DutchPatrick** [comment]
I do.

--------------------------------------------------
Greetings,
Patrick


2015-06-12 2:15 GMT+02:00 Brett Smith <notifications@github.com>:

**Comment by 00875** [comment]
Your sql db is corrupt. Delete sv.db or recovery it
