### ISSUE TITLE
Ulx mute or gimp doesn't work.

### ISSUE THREAD

**Issue by ickycoolboy** [Nayruden/Ulysses#475]
The Player can still chat normally even after it says in the chat "player" has been muted

**Comment by MStruntze** [comment]
Can't reproduce. Are you running the latest version? Which gamemode are you running? Do you have any other admin mods or addons in general that might interfere with this?

**Comment by SticklyMan** [comment]
Also can't reproduce. If this is still an issue, try posting on our forums at http://forums.ulyssesmod.net with more information, and we can help you out there.
