### ISSUE TITLE
Just a bunch of errors.

### ISSUE THREAD

**Issue by DutchPatrick** [Nayruden/Ulysses#477]
I installed ULX and ulib and Utime from here on my DarkRP server, and i just get a bunch of errors.
When doing ulx menu i get Player is not authed
XGUI error
also
] rcon ulx adduser patrick superadmin

[ERROR] addons/ulx/lua/ulx/modules/sh/user.lua:57: attempt to index local 'userInfo' (a nil value)
  1. call - addons/ulx/lua/ulx/modules/sh/user.lua:57
   2. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
    3. unknown - addons/ulib/lua/ulib/shared/commands.lua:1296
     4. unknown - lua/includes/modules/concommand.lua:54

Please help me.

**Comment by Nayruden** [comment]
You're almost certainly getting errors before this point. What else do you see in the console?

**Comment by Nayruden** [comment]
No response in a long time, no other users have reported any similar errors; closing.
