### ISSUE TITLE
Upon selecting something in a Drop-Down menu, the order of items is broken

### ISSUE THREAD

**Issue by doctorluk** [Nayruden/Ulysses#479]
Using two examples, you can see that XGUI swaps two elements on the !menu. I'm using SourceBans (an external plugin) and User Management -> adduserid in this example:

sbanid default look:
http://i.imgur.com/VqzogwJ.jpg
Upon entering any kind of string to the text field and clicking the duration, the buttons are swapped:
http://i.imgur.com/QZvqCoh.jpg

adduserid default look:
http://i.imgur.com/fOiezlC.jpg
Upon entering any kind of string to the text field AND THEN selecting a group, the buttons are swapped:
http://i.imgur.com/FO3T8K7.jpg

I'm noticing this behaviour since I've updated to XGUI V15.6.1 from this repository.

**Comment by CHarrisMedia** [comment]
How have you got Sourcebans and ULX working together?

**Comment by doctorluk** [comment]
I've found a module for ULX while googling for it. I don't have the exact source, but it was on facepunch.

**Comment by CHarrisMedia** [comment]
Was it this by any chance? 
http://facepunch.com/showthread.php?t=1311847

**Comment by doctorluk** [comment]
Yep.

**Comment by CHarrisMedia** [comment]
There's only 404 errors now, do you still have the files you could possibly share?

**Comment by doctorluk** [comment]
It may not be 100% original since I've entered my details and removed them again inside the .zip file, but I think I've cleaned it up properly.
https://dl.dropboxusercontent.com/u/31140690/ULX%20Source%20Bans%20v0.2.3a.zip?dl=1

**Comment by CHarrisMedia** [comment]
Got it! Thanks a lot for that, I really needed those files and have spent about 3 hours looking for them! Much appreciated, I guess I just have to follow the rest of the tutorial on face punch?

**Comment by doctorluk** [comment]
Yes, just follow the tutorial as usual. And please pay attention to my EDIT above, I've removed the adduser functionality and rely on my gameserver's group settings only.

**Comment by CHarrisMedia** [comment]
Will do, I too don't really want Sourcebans dealing with ranks ingame just incase my account got hijacked or something.

**Comment by doctorluk** [comment]
Alright, good luck!

**Comment by CHarrisMedia** [comment]
Thanks again :)

**Comment by SticklyMan** [comment]
This appears to be an issue with DTextEntry children in a DListLayout. I've made an issue about it on the Garry's Mod issue tracker, but I'll see if I can find a workaround in the meantime.

https://github.com/Facepunch/garrysmod-issues/issues/2175

**Comment by doctorluk** [comment]
Thanks a bunch! Looks like the problem has been discussed.
