### ISSUE TITLE
Ulx close in Rounds

### ISSUE THREAD

**Issue by marllonlb** [Nayruden/Ulysses#481]
wenn i´m alive and its a active Round and i tippe in !menu ulx colse immediately what is the problem for that?

**Comment by Nayruden** [comment]
What gamemode?

**Comment by marllonlb** [comment]
its the gamemode TTT before the update of gmod i didnt had this problem (sorry for bad englisch)

**Comment by YourStalker** [comment]
I don't have this issue on the newest ULX and TTT

**Comment by deinemudda32** [comment]
Me too.

**Comment by Nayruden** [comment]
Does not seem to be a problem that affects anyone else, closing.
