### ISSUE TITLE
ULX crashes server

### ISSUE THREAD

**Issue by willwill181** [Nayruden/Ulysses#482]
No idea why this happens but everytime a ulx command is executed the  server crashes. I have the lastest version of everything. TTT up to date. ULX/ULib up to date. Gmod version upt to date.

**Comment by YourStalker** [comment]
It's most likely some other addon fucking your shit up

**Comment by deinemudda32** [comment]
Happens on adding users or banning people if txt files are full.

**Comment by Nayruden** [comment]
Could be related to saving to text files (for which an issue is already open). Otherwise, this is beyond the control of ULX.
