### ISSUE TITLE
ULX Get MOTD from URL Grayed out.

### ISSUE THREAD

**Issue by XenZibe** [Nayruden/Ulysses#484]
Upon going into ULX General settings the option to tick get MOTD from URL is grayed out and I have no way to tick it allow the text box to be unlocked for me to enter a URL.
![dua9zcpvp9vd6zbf](https://cloud.githubusercontent.com/assets/9489645/8605592/47de247a-267e-11e5-9dbc-cba933c7c552.png)

**Comment by MrUnknownGamer** [comment]
I'll see if I can fix this.

**Comment by Violat0r** [comment]
Known issue see #470

**Comment by PokeguySR** [comment]
Has this issue been fixed yet? I really need the MOTD to work again.

**Comment by Violat0r** [comment]
No it has not. You may manually fix this by changing manually add it to garrysmod/data/ulx/config.txt by changing the line ulx showMotd "yoururl" hope this helps.

**Comment by XenZibe** [comment]
@Violat0r You mean something like this?


ulx_showMotd "yoururl*replaced*" ; Set to 0 to disable showing motd on connect. Shows the file the cvar motdfile says to.
; Set showMotd 1

**Comment by Violat0r** [comment]
no underline needed just
ulx showMotd "yourwebsiteurl.com"  ; Set to 0 to disable showing motd on connect. Shows the file the cvar motdfile says to.

everything after the ; is just a comment.

**Comment by SticklyMan** [comment]
Fixed in b8b5c30d09768fc78522ebde044244115fceae70
