### ISSUE TITLE
problem with the ulx.fancyLogAdmin command

### ISSUE THREAD

**Issue by Stealthycow** [Nayruden/Ulysses#485]
Hello,
    I have been having a small issue. The fancyLogAdmin command works for code that I wrote a while ago or code, imported; however, when i try to create a new file and use that function, it doesn't want to work.
Can someone point me to a page that describes the functionality of fancyLogAdmin and possibly give me a reason as per why Garry's Mod is being selective in which fancyLogAdmin chats to display
Thank you

**Comment by Nayruden** [comment]
Thanks for your interest, @Stealthycow, but this area is for bug reports only. Please go to our forums and we'd love to help you there.
