### ISSUE TITLE
ULX Menu error help

### ISSUE THREAD

**Issue by willywanka** [Nayruden/Ulysses#487]
I can type the commands in chat and they work . But when I get on ulx menu and access the command it kills my menu. Causing it to block my screen and not being able to close the menu and results in a script error.

[ERROR] addons/ulx/lua/ulx/modules/cl/xgui_helpers.lua:302: attempt to perform arithmetic on local 'maxvalue' (a nil value)
  1. x_getcontrol - addons/ulx/lua/ulx/modules/cl/xgui_helpers.lua:302
   2. obj - addons/ulx/lua/ulx/xgui/commands.lua:210
    3. func - addons/ulx/lua/ulx/modules/cl/xlib.lua:1098
     4. animQueue_call - addons/ulx/lua/ulx/modules/cl/xlib.lua:1079
      5. func - addons/ulx/lua/ulx/modules/cl/xlib.lua:1098
       6. animQueue_call - addons/ulx/lua/ulx/modules/cl/xlib.lua:1079
        7. animQueue_start - addons/ulx/lua/ulx/modules/cl/xlib.lua:1066
         8. OnSelect - addons/ulx/lua/ulx/xgui/commands.lua:109
          9. unknown - lua/vgui/dlistview_line.lua:94

**Comment by matiasg90** [comment]
idem!
