### ISSUE TITLE
ULX Launch error

### ISSUE THREAD

**Issue by TheVoicedFlame** [Nayruden/Ulysses#488]
So, when ever i try to open the menu, it it says my ulx has not been authed, what does that mean?

**Comment by 00875** [comment]
It means what ULX can not load your group. Maybe corrupted files or (primarily) addon conflict (or bad addon)

**Comment by Nayruden** [comment]
You've got much larger issues, and probably errors showing way before that point. Please contact me on Steam or the team on the forums for further help.
