### ISSUE TITLE
Advert and OOC

### ISSUE THREAD

**Issue by WBGJayceGaming** [Nayruden/Ulysses#493]
For some reason ooc and advert broke.

Before: [OOC]NAME lol or [Advert]NAME raid

After: lolNAME lol Its the same with advert lolNAME lol

I tried to fix it by uninstalling a chat tags addon but that didn't work.

Is there a folder for ooc and advert prefixes?

Please help.

**Comment by YourStalker** [comment]
ULX doesn't even have an ooc or advert feature. It also sounds like you got hacked.

**Comment by 00875** [comment]
This is not ULX. You use DarkRP

**Comment by zpetty33** [comment]
This is the github for the Ulysses projects. Please do not start
discussions here for unrelated works such as DarkRP.
