### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by isrmafia** [Nayruden/Ulysses#496]
[ERROR] addons/utime/lua/autorun/cl_utime.lua:310: attempt to index local 'cpane
l' (a nil value)
  1. buildCP - addons/utime/lua/autorun/cl_utime.lua:310
   2. resetCvars - addons/utime/lua/autorun/cl_utime.lua:305
    3. fn - addons/utime/lua/autorun/cl_utime.lua:334
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

what is it about ? and is there a fix?

**Comment by 00875** [comment]
Thir error exists for ages, and that still doesn't fixed. Why?

**Comment by Nayruden** [comment]
Mostly because I've never been able to reproduce it. Without being able to reproduce it, I generally have no idea how to fix it.

**Comment by deinemudda32** [comment]
Just check for cpanel is valid before the line should fix it :P

**Comment by Nayruden** [comment]
Possibly fixed with f5eab1884b5c49a3aa0328cf45dd801f1f9ebc75. I don't understand why I've never been able to replicate this error, but if it's happening the way I think it might be, that ought to fix it without other side affects.
