### ISSUE TITLE
Implement CAMI

### ISSUE THREAD

**Issue by FPtje** [Nayruden/Ulysses#497]
The time is now!

https://docs.google.com/document/d/1QIRVcAgZfAYf1aBl_dNV_ewR6P25wze2KmUVzlbFgMI/edit
https://github.com/FPtje/DarkRP/issues/2073

DarkRP has it implemented:
https://github.com/FPtje/DarkRP/commits/cami

The commits of July 21 and 22 show an example implementation. Like I said in the e-mail, there's a lot you can do completely differently, so take it as an example, not as a guide :+1:

**Comment by YourStalker** [comment]
How much, if at all, will something like this fuck with currently existing ULX plugins?

**Comment by FPtje** [comment]
I don't think it will fuck up anything. CAMI adds some hooks and functions
and syncs usergroups between Admin mods. Optionally it also provides a
standard interface for the privilege system of an admin mod.

Plugins won't notice the slightest thing depending on how ULX implements
it. I'm sure a conflictless implementation is possible.

**Comment by Nayruden** [comment]
It's on the list, but I'm moving and without a computer for a few days. That is, don't expect me to be able to immediately implement this.

**Comment by 00875** [comment]
Good Times!

**Comment by FPtje** [comment]
Nice!!
