### ISSUE TITLE
ULX Rank Disappears

### ISSUE THREAD

**Issue by Speeddemond123** [Nayruden/Ulysses#498]
We are running on the newest version of ULX however we are having a problem that seems to hit a lot of people, the ULX ranks are disappearing upon enter of the server. Multiple things have been done to try and fix this however none have seemed to work. The strange part is that it is only affecting 2 out of 10 servers, gamemodes being Deathrun and Hide and Seek.

 It would be greatly appreciated if you could contact us so we can get this resolved as soon as possible:

People To Contact 
-http://steamcommunity.com/id/whereswaldoohwait/
-http://steamcommunity.com/id/dbeard2/

**Comment by Speeddemond123** [comment]
Update, 3 out of 10 Gmod servers are having this problem.

**Comment by 00875** [comment]
#463 #461 #460 #435 Welcum! You're Not One! So, this is Dublicate

**Comment by Speeddemond123** [comment]
Its happening on multiple servers, Prophunt, Deathrun, and Hide and seek. We've looked at the previous reports however none of them seem to give us any way or any ideas to fix it. We really need help trying to fix this.

**Comment by zpetty33** [comment]
This issue is likely caused by file permission issues.
Make sure your data directory and all of the sub-directories that ULX/ULib use are writable.

**Comment by 00875** [comment]
>Prophunt, Deathrun, and Hide and seek

#494

**Comment by AMD-NICK** [comment]
I have this problem too

**Comment by AMD-NICK** [comment]
It's looks like fix https://github.com/Nayruden/Ulysses/issues/463#issuecomment-101900210 :)

**Comment by Nayruden** [comment]
We've only seen this on DarkRP or due to permission problems in the past. Please contact me directly so we can figure out what's going on with your server, if you're still experiencing it.
