### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by ttt141** [Nayruden/Ulysses#501]
Upon a player joining, everyone gets this error.

[ERROR] lua/includes/extensions/table.lua:74: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Merge - lua/includes/extensions/table.lua:74
    3. fn - addons/ulx/lua/ulx/cl_lib.lua:22
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/extensions/net.lua:32

And when I try to enable maps for "allowed votemaps" I get this error.

[ERROR] addons/ulx/lua/ulx/xgui/server/sv_settings.lua:218: bad argument #1 to 'insert' (table expected, got nil)
  1. insert - [C]:-1
   2. unknown - addons/ulx/lua/ulx/xgui/server/sv_settings.lua:218
    3. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:53
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by Nayruden** [comment]
Sorry for taking so long on responding to this. It looks like ulx.votemaps may have been deleted on your client/server. Try running ULX/ULib ONLY. I suspect some other addon is removing that table.

**Comment by Nayruden** [comment]
No response, unable to duplicate.
