### ISSUE TITLE
More deprecated stuff

### ISSUE THREAD

**Issue by Fuzzik** [Nayruden/Ulysses#502]
I missed a few uses of deprecated functions in my original PR, so I'll just bring it to attention here.

umsg to net library
Couple of uses of the umsg library that could hopefully be converted to net

Panel:SetToolTip
ulx/lua/ulx/modules/cl/xlib.lua
ulx/lua/ulx/xgui/groups.lua

Panel:AddText
ulib/lua/ulib/shared/messages.lua

DPanel:SetDrawBackground
ulx/lua/ulx/modules/cl/xlib.lua

**Comment by SticklyMan** [comment]
Thanks for keeping up with these! It is very helpful for us. Some notes FYI:

I will let Megiddo decide what to do with usermessages- Unless I'm mistaken, they're not deprecated and won't be removed any time soon, but it may be beneficial to use the newer libraries.

I'm not finding any information about SetToolTip being deprecated- do you have more information about it? It's still being used in quite a few places within TTT and GMod as well.

ulib/shared/messages.lua is not calling Panel:AddText, but chat.AddText. It's pretty close though. :P

I'm using SetDrawBackground on sliders to undo this line of code:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/vgui/dnumslider.lua#L21
I haven't found an alternative that would work, so I'm going to leave it until they change something with the sliders.

**Comment by Nayruden** [comment]
I very much doubt that umsgs will go away anytime soon, and there's no compelling reason for us to change those to anything else. 

Thanks for bringing these to our attention!

**Comment by Fuzzik** [comment]
@SticklyMan I was just going off of the Gmod wiki for these. Panel:SetToolTip is here http://wiki.garrysmod.com/page/Panel/SetToolTip

It's an alias of Panel:SetTooltip, just different capitalization.

**Comment by SticklyMan** [comment]
Ah, good catch- I completely missed that. Got it fixed, thanks!
