### ISSUE TITLE
ULX Vote, Unable to vote (Only my client)

### ISSUE THREAD

**Issue by Matt0905** [Nayruden/Ulysses#507]
I have a very irritating issue that disallows any ability for me to participate in Ulx Votes. It doesn't allow me to Vote even when i press the number keys. Although i can vote in other Game Mode type votes (i.e Voting for maps(Not using ULX))

It has always been this way and I haven't found anyone else with this issue.

Some image proof here. When pressing an echo for me voting does not appear.

https://i.gyazo.com/a76ebbab7b472a2670f7050cc1b2d9a1.png

Thank you for your time and i hope you can fix my issue.

**Comment by Nayruden** [comment]
Did you re-bind your number keys? Though, we are hooking keys the same way
any other vote mechanism does.

**Comment by Matt0905** [comment]
I have not re-binded any of the keys. I can vote on our Deathrun's Map votes.

**Comment by Matt0905** [comment]
Ah i found the issue. Any others who may find this issue, it is because your number must be bound to slot(number) (e.g number 2 would be bound to "slot2".

But thank you for your time.

ISSUE RESOLVED
