### ISSUE TITLE
ULib doesn't load CAMI privs registered before ULib loads

### ISSUE THREAD

**Issue by FPtje** [Nayruden/Ulysses#509]
Reproducing:
1. Install the FPP Addon
2. Start sandbox (not DarkRP, because the FPP in DarkRP loads *after* ULib)
3. The privileges won't register, ULX will deny access by default.

I put a `print(ULib)` right under the `CAMI.registerPrivilege` lines in FPP, it showed `nil`. 
I've had the same bug in FAdmin. [This is how I solved it](https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/fadmin/fadmin/access/sh_shared.lua#L122). 

So yeah, the solution is both to listen to the hook and iterate over all currently existing privileges to make sure those are registered with your admin mod as well.

**Comment by FPtje** [comment]
Issue was originally reported to FPP: https://github.com/FPtje/Falcos-Prop-protection/issues/135

**Comment by itswonky** [comment]
Worked. Thank you so much.

**Comment by FPtje** [comment]
The point is that the problem isn't there in DarkRP because DarkRP loads *after* ULib.

**Comment by itswonky** [comment]
So how do I get the gamemode on DarkRP and get my privs
