### ISSUE TITLE
CAMI Does not Work

### ISSUE THREAD

**Issue by 00875** [Nayruden/Ulysses#510]
![2015-08-28_17-06_garry s mod](https://cloud.githubusercontent.com/assets/6339511/9544000/7a8c27c8-4da7-11e5-96a8-bf1a53ed5e71.jpg)
![2015-08-28_17-06_ponyrp rc 0 19 - eat t](https://cloud.githubusercontent.com/assets/6339511/9544001/7c7db3d0-4da7-11e5-9945-4586d2bf098e.jpg)
No comment

**Comment by Nayruden** [comment]
Oops, that was a silly error on my part. Sorry about that.
