### ISSUE TITLE
game breaking errors

### ISSUE THREAD

**Issue by kulcris** [Nayruden/Ulysses#511]
L 08/29/2015 - 14:20:16: Lua Error: 
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/modules/slots.lua:44
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/modules/slots.lua:44
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/modules/slots.lua:44
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
Dropped [PieBald]Peklenc from server (Disconnect by user.)
L 08/29/2015 - 14:20:17: "[PieBald]Peklenc<9><STEAM_0:0:26179978><>" connected, address "70.119.110.58:27005"
Client "[PieBald]Peklenc" connected (70.119.110.58:27005).
L 08/29/2015 - 14:20:17: "[PieBald]Peklenc<9><STEAM_0:0:26179978><>" STEAM USERID validated
L 08/29/2015 - 14:21:24: Lua Error: 
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
2. Call - addons/ulib/lua/ulib/shared/hook.lua:179
3. fn - addons/ulib/lua/ulib/server/ucl.lua:881
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
5. UniqueID - [C]:-1
6. LoadLuaDataOptions - addons/libk/lua/libk/3rdparty/luadata.lua:203
7. fn - addons/libk/lua/libk/3rdparty/luadata.lua:215
8. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
2. Call - addons/ulib/lua/ulib/shared/hook.lua:179
3. fn - addons/ulib/lua/ulib/server/ucl.lua:881
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
5. UniqueID - [C]:-1
6. LoadLuaDataOptions - addons/libk/lua/libk/3rdparty/luadata.lua:203
7. fn - addons/libk/lua/libk/3rdparty/luadata.lua:215
8. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
2. Call - addons/ulib/lua/ulib/shared/hook.lua:179
3. fn - addons/ulib/lua/ulib/server/ucl.lua:881
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
5. UniqueID - [C]:-1
6. LoadLuaDataOptions - addons/libk/lua/libk/3rdparty/luadata.lua:203
7. fn - addons/libk/lua/libk/3rdparty/luadata.lua:215
8. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
Printing Table from s at addons/libk/lua/libk/server/sv_libk_player.lua:23 :
Object Instance KPlayer
{
player = STEAM_0:0:26179978
updated_at = 1440857939
uid = 2958061439
id = 1
steam64 = 76561198012625684
class = class KPlayer
name = [PieBald]Peklenc
created_at = 1440439895
}
{
Mold = 0
Gold = 0
Rock = 2
A Rock = 0
Silver = 0
}
L 08/29/2015 - 14:21:24: Lua Error: 
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/base.lua:73
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/base.lua:73
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] Unauthed player
1. query - [C]:-1
2. fn - addons/ulx/lua/ulx/base.lua:73
3. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
L 08/29/2015 - 14:21:24: Lua Error: 
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
1. fn - addons/ulx/lua/ulx/modules/uteam.lua:23
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
[ERROR] addons/ulx/lua/ulx/modules/uteam.lua:23: attempt to index a nil value
L 08/29/2015 - 14:21:24: "[PieBald]Peklenc<9><STEAM_0:0:26179978><>" entered the game
L 08/29/2015 - 14:21:25: Lua Error: 
[ERROR] Unauthed player
1. query - [C]:-1
2. getWalletChangeSubscribers - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:8
3. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:50
4. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
5. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
6. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
7. sendWallet - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:48
8. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:333
9. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
10. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
11. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
12. initPlayer - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:331
13. unknown - addons/pointshop2/lua/ps2/server/sv_pointshopcontr
[ERROR] Unauthed player
1. query - [C]:-1
2. getWalletChangeSubscribers - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:8
3. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:50
4. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
5. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
6. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
7. sendWallet - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:48
8. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:333
9. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
10. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
11. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
12. initPlayer - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:331
13. unknown - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:368
[ERROR] Unauthed player
1. query - [C]:-1
2. getWalletChangeSubscribers - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:8
3. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:50
4. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
5. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
6. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
7. sendWallet - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller_wallet.lua:48
8. s - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:333
9. succ - addons/libk/lua/libk/shared/1_sh_promises.lua:48
10. Done - addons/libk/lua/libk/shared/1_sh_promises.lua:116
11. Then - addons/libk/lua/libk/shared/1_sh_promises.lua:107
12. initPlayer - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:331
13. unknown - addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua:368
Timer Failed! [Simple][@addons/pointshop2/lua/ps2/server/sv_pointshopcontroller.lua (line 364)]
L 08/29/2015 - 14:21:31: Lua Error: 
[ERROR] addons/ulx/lua/ulx/modules/xgui_server.lua:52: attempt to index field 'cmds' (a nil value)
1. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:52
2. unknown - lua/includes/modules/concommand.lua:54
[ERROR] addons/ulx/lua/ulx/modules/xgui_server.lua:52: attempt to index field 'cmds' (a nil value)
1. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:52
2. unknown - lua/includes/modules/concommand.lua:54
[ERROR] addons/ulx/lua/ulx/modules/xgui_server.lua:52: attempt to index field 'cmds' (a nil value)
1. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:52
2. unknown - lua/includes/modules/concommand.lua:54

causes client side lua to not load properly

**Comment by kulcris** [comment]
a server restart always fixes it but every morning when i get on i have greyed out dev models and hud not loading

**Comment by Nayruden** [comment]
Sorry for not getting back to you sooner. No one else has reported any issues like this. Are you still experiencing this problem?

**Comment by Nayruden** [comment]
No response, unable to duplicate.
