### ISSUE TITLE
Improve performance of ULX and ULib

### ISSUE THREAD

**Issue by WGHydrogen** [Nayruden/Ulysses#513]
You can easily improve performance of ULX and ULib by converting the usermessages to net messages. Please do so.

**Comment by MStruntze** [comment]
How does it improve performance?

**Comment by MrUnknownGamer** [comment]
Oh god. Here we go.

**Comment by WGHydrogen** [comment]
net messages are faster and can carry more data than usermessages.

**Comment by MStruntze** [comment]
How do you know it's faster? They can indeed carry more data, but I believe they're only used where they don't exceed their limit.

**Comment by Nayruden** [comment]
Thanks for the suggestion, but usermessages are not sent anywhere close to frequently enough for us to be concerned about performance in that regard.

**Comment by Nayruden** [comment]
That all being said, I probably will convert it over at some point, but performance wouldn't enter into the list of top 20 reasons why I was doing it. ;)
