### ISSUE TITLE
PlayerArg return calling_ply

### ISSUE THREAD

**Issue by comedinha** [Nayruden/Ulysses#515]
I try put
```
give:addParam{ type=ULib.cmds.PlayerArg, ULib.cmds.optional }
```
if i say !test
target_ply return calling_ply, not return ""
if i say !test otherplayer
target_ply return the otherplayer

Would have any way to target_ply return nil or ""?

**Comment by Nayruden** [comment]
I don't understand what you're asking for. If you just want to test if target_ply == calling_ply, then you can easily add such a conditional at the top of the function. In any case, this is not an "issue" with ULX/ULib (this area is for issues only).

**Comment by comedinha** [comment]
I try creste a command with 2 functions...
If player say !Test open a menu, if say !Test {pname} execute the command.
But it i say only "!Test" target_ply return calling_ply, not return nil

**Comment by comedinha** [comment]
@Nayruden ?

**Comment by zpetty33** [comment]
This has been closed. This is not an issue with ULX/ULib but more an issue with you not setting up custom functions properly. If you would like assistance, please register on our forums and post a topic there. Further posts here will not be answered. Thank you.
