### ISSUE TITLE
Clients don't know whether they have CAMI privs

### ISSUE THREAD

**Issue by FPtje** [Nayruden/Ulysses#516]
The CAMI spec didn't mention anything about which realms CAMI should be implemented in. This turned out to be a mistake on my part. ULib has CAMI implemented only serverside, which makes intuitive sense, but causes some problems with CAMI compliant addons.

Some examples:
In FPP, the buttons in the FPP settings menus are disabled when you don't have the privilege. One could give FPP CAMI privileges to any usergroup (say operator), but because the client doesn't have any knowledge about that, it falls back on the default `ply:IsSuperAdmin()` and `ply:IsAdmin()` functions. In this example operators can't click any of the buttons in the FPP menu.

DarkRP has the same problems with manipulating doors (setting them to unownable, owned by a certain group etc.). When operators (with the appropriate CAMI privs) open the keys menu, those options are hidden because the client thinks they don't have access.

The most reasonable way to solve this is to demand from admin mods to implement CAMI shared. I take full responsibility for not putting this in the spec in the first place. I'm very sorry about that.

**Comment by Awesome123123** [comment]
This needs to be fixed soon!

**Comment by kulcris** [comment]
the latest "stable" version seems to work atm without cami, use that until they fix this (right now custom groups crash if they so much as buy a door)

**Comment by Nayruden** [comment]
CAMI stuff is still on the "todo" list, I'm hoping to get to it in the next week.

**Comment by Hazbelll** [comment]
Gonna have to bump this. I'm still waiting on CAMI being implemented Clientside before I update ULib and ULX for my own Server to the latest version.

**Comment by Hazbelll** [comment]
Any progress or updates on this at all? @Nayruden gave an E.T.A of a week and it's now been just over a month since.

**Comment by 00875** [comment]
@Nayruden have no time now.

**Comment by Nayruden** [comment]
Unfortunately true, but it's still a top priority (among many others) for me.

**Comment by Nayruden** [comment]
Alright, @FPtje, this is fixed/implemented now. I'm not sure exactly what you had in mind as far as server/client collaboration, but this should address the immediate problems.
