### ISSUE TITLE
sv_bans.lua:152: attempt to compare string with number

### ISSUE THREAD

**Issue by deinemudda32** [Nayruden/Ulysses#517]
[ERROR] addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152: attempt to compare string with number
  1. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152
   2. sort - [C]:-1
    3. getSortTable - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:152
     4. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:193
      5. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:65
       6. unknown - lua/includes/modules/concommand.lua:54

**Comment by Nayruden** [comment]
@deinemudda32, please use a more descriptive title in the future.

**Comment by Nayruden** [comment]
@SticklyMan, nothing jumps out at me during my quick review of the code as an obvious cause, though I'm guessing some sort of integrity check in bans.getSortTable for the bans table would probably be a good idea. Or something somewhere to ensure the data is in the format you expect, if not already present.

@deinemudda32, are you doing anything in particular to get this error?

**Comment by deinemudda32** [comment]
Nope. Just showed up.
