### ISSUE TITLE
XGUI is not showing up in my tab! 

### ISSUE THREAD

**Issue by basiically** [Nayruden/Ulysses#520]
Basically, I'm new to ULX and ULIB, and that everything was working perfectly fine, I had no problems, and it was great, than, I accidently set a new group as a superadmin, and now all I can see on my ULX menu is my CMDS, Settings, and Maps. I cant manage permissions or even manage groups by using the menu, I couldn't find any possible way to fix this, I deleted the files and reinstalled them 10 or more times. I really need to fix this before I release my server, I also have screenshots, please help, and I also gave myself superadmin using my SRCDS, but I never got the chance to have access to all commands and I cant fix it :(!

Please help, and thank you!

Screenshots:

![gm_construct0036](https://cloud.githubusercontent.com/assets/14812094/10068624/d8b394b6-62b6-11e5-9b58-21f0167625b1.jpg)
![gm_construct0037](https://cloud.githubusercontent.com/assets/14812094/10068621/d8afc26e-62b6-11e5-981e-f551f2e9c1fd.jpg)
![gm_construct0038](https://cloud.githubusercontent.com/assets/14812094/10068622/d8afe46a-62b6-11e5-93f0-fa92d4378b15.jpg)
![gm_construct0039](https://cloud.githubusercontent.com/assets/14812094/10068623/d8b333fe-62b6-11e5-8f6a-479ca3690086.jpg)

**Comment by SticklyMan** [comment]
The fastest way to reset your groups and permissions to defaults would be to remove your SERVER's garrysmod\data\ulib\groups.txt file, and restart your server. This should generate a new groups file with the permissions you need.

However, to answer your question directly, you can regain access to XGUI menus by granting your group following accesses. You must run these as RCON, or in your server console: (Replace 'superadmin' with the group you belong to)
ulx groupallow superadmin xgui_gmsettings
ulx groupallow superadmin xgui_managebans
ulx groupallow superadmin xgui_managegroups
ulx groupallow superadmin xgui_svsettings

You may also want to give your group access to groupallow as well:
ulx groupallow superadmin "ulx groupallow"

For future reference, please post on our forums at forums.ulyssesmod.net if you have any further help & support questions, as this is not the correct place.
