### ISSUE TITLE
ULX Layout Broken

### ISSUE THREAD

**Issue by Mmgamer01Playz** [Nayruden/Ulysses#521]
I have been looking around in my client side ULX settings when I saw we could  change layouts, so I changed to all of them seeing what one i liked best but when I got to the last one it broke my ULX so I can't use any of the tabs ect. ect.

If you need console stuff I have it here:

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:92: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:92
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. unknown - lua/vgui/dpropertysheet.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:92: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:92
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. unknown - lua/vgui/dpropertysheet.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. unknown - lua/vgui/dpropertysheet.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. unknown - lua/vgui/dpropertysheet.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. unknown - lua/vgui/dpropertysheet.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dbutton.lua:91: attempt to index field 'Button' (a nil value)
1. UpdateColours - lua/vgui/dbutton.lua:91
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. PerformLayout - lua/vgui/dlabel.lua:94
4. unknown - lua/vgui/dbutton.lua:113
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:90: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:90
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:92: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:92
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:90: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:90
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:92: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:92
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

Crazy physics on [176][prop_physics] [Ang:-10.696133,-71.782852,11.191429] [Pos:16384.292969,-2317.734863,6979.943848] - removing
ServerLog: prop_physics(models/props_junk/sawblade001a.mdl) Got removed
[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:98: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:98
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:112

[Mmgamer01 Playz|3|STEAM_0:0:74570161] Lua Error:

[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
1. UpdateColours - lua/vgui/dpropertysheet.lua:100
2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
4. unknown - lua/vgui/dpropertysheet.lua:65
5. InvalidateLayout - [C]:-1
6. unknown - lua/vgui/dlabel.lua:121

**Comment by SticklyMan** [comment]
Can you send me the theme or name of theme you selected? Derma themes are not common anymore, and it's very likely that old themes will be severely broken, and there's not much I can do to fix them. I would recommend avoiding them for now.

**Comment by Mmgamer01Playz** [comment]
I don't know what theme I had do you think you could tell me the list? Ill probably spot it

**Comment by SticklyMan** [comment]
ULX/ULib do not come with any Derma themes- we just use the default. Any other themes would be manually added or come from addons, gamemodes, etc.

**Comment by Mmgamer01Playz** [comment]
Oh, great now I need to go through all of the addons :P thanks for telling me that anyways

**Comment by Nayruden** [comment]
Did you find which one was the issue, @Mmgamer01Playz?

**Comment by Mmgamer01Playz** [comment]
No, I think it is one of the normal themes as I went on a no-addon server only ULX with no extra themes and it still is broken

**Comment by Nayruden** [comment]
Themes are client side, it doesn't matter what the server has.

**Comment by Mmgamer01Playz** [comment]
I've looked through all my addons and none of them sound like they change
the themes, is there a way I can just re-install ULX so it uses the normal
theme again?

**Comment by SticklyMan** [comment]
Try checking your client's \data\ulx\xgui_settings.txt file (if it exists) to see what theme it's attempting to use, then reset it to the default.

Here's a post I made with a bit more detail on a related issue:
http://forums.ulyssesmod.net/index.php/topic,8814.msg45138.html#msg45138

**Comment by Mmgamer01Playz** [comment]
It had nothing about a "skin" bit in the .txt so I just deleted it like you
said

**Comment by SticklyMan** [comment]
Did that help alleviate your problem? Or are you still getting the errors?

**Comment by Mmgamer01Playz** [comment]
Yeah its fine now. Thanks!

**Comment by SticklyMan** [comment]
Interesting- I just tried removing the skin line from my xgui_settings.txt, but did not get the same errors as you (It defaults to "Default" skin if it's not specified), so I'm not quite sure what went wrong. But either way, glad you got it working!
