### ISSUE TITLE
Newest ULib/Ulx doesn't create default files in data folder, resulting in errors on startup

### ISSUE THREAD

**Issue by iSnipeu** [Nayruden/Ulysses#523]
Clean install after start up, haven't touched data folder
![Image](http://i.imgur.com/GZjRZSH.png)

Manually copied the default files from the addon folders into the data folder
![Image](http://i.imgur.com/2InfT0a.png)

I haven't looked into it any further, but it could be a result of https://github.com/Nayruden/Ulysses/commit/5f2d3cd9a0cda728fef17851eba421c6f6ae0dd4

**Comment by Nayruden** [comment]
Thank you. Will fix this ASAP.
