### ISSUE TITLE
Question: Player-NextBot

### ISSUE THREAD

**Issue by originalwhitestar** [Nayruden/Ulysses#524]
Uhm, i wanted to ask if its possible to make ULX work even when there are Player-Nextbots on the server? Everytime I make such an nextbot join, ULX gives out the default unauthed error, making TTT etc stop running. :/

**Comment by Nayruden** [comment]
I'm assuming you're using the release version of ULX/ULib, as this was addressed in the development version (#447). Sorry it hasn't hit release yet, hopefully we'll get it out soon.
