### ISSUE TITLE
ULX Group Managment Problem

### ISSUE THREAD

**Issue by Dirtbike115** [Nayruden/Ulysses#525]
There was once an "Owner" group on my Group Management. Today, the group "Owner" had suddenly disappeared. So, I created an "Owner" group and I forgot to put Permissions on the group and I put my name in the "Owner" group which doesn't have any powers. Now I can't get my group back that has all the powers. I'm limited to the powers now. I've reinstalled ULX and it still won't reset it right. Anyone know how to reset it correctly so I can get all my powers back?

**Comment by Nayruden** [comment]
This is not the area for help and support, but type "ulx adduser <your name> superadmin" in the server console and you'll have all permissions again.
