### ISSUE TITLE
URM restriction mod not restricting

### ISSUE THREAD

**Issue by ThePyromanic** [Nayruden/Ulysses#526]
So I needed a replacement for URS since i have a lot of ranks on my server and since the UI of URS gets super clustered, I started to use URM as its replacement. It's probably one of the best restriction mods ive ever used in my gmod experiance but there is an issue. 

Whenever I restrict something for example a SWEP for the rank "user", once ive changed my rank to "user" and i try spawning that SWEP, it lets me spawn it but the error message ("THIS ITEM IS RESTRICTED") still shows up even though they can still spawn the SWEP. Is this a rank error or something to do with the mod? 

I've tried explaining this the best I can and if someone wants a quick video flythrough of the problem, I'd be more than happy to do so but if someone has a fix for this, could you plz tell?

Thank you.

**Comment by Nayruden** [comment]
Sorry, @ThePyromanic, but URM is not maintained by Team Ulysses, and we are unable to help you. Please contact the developer on the forums or via email.

**Comment by Weol** [comment]
This is a known issue. URM does this on servers that run the GitHub version of ULX,.

I have not found the cause of this, but until it is resolved I recommend you use the one you can find ulyssesmod.net.
