### ISSUE TITLE
not detected

### ISSUE THREAD

**Issue by IvyMercyLyons** [Nayruden/Ulysses#530]
well, so after three weeks of having ulx in my addons i have not once been able to use it; binding xgui and using the key brings up an error, commands are nonexistent and it is absolutely unnoticeable that i actually have the addon at all; is this dead as happened to evolve?

**Comment by SticklyMan** [comment]
Nope- we're still very much alive and kicking. You must have it installed incorrectly, or something is not configured properly. Are you running this on a windows or a linux server?

**Comment by Nayruden** [comment]
@IvyMercyLyons -- this is not the area for help and support, but bug
reports only. Please go to the forums for help getting ULX setup.

**Comment by Nayruden** [comment]
@SticklyMan, you sniped me. So much for being dead and inactive. ;)

**Comment by SticklyMan** [comment]
It's all good. ;) Our forums are located here: http://forums.ulyssesmod.net/
Feel free to sign up and create a new thread and we can help you further.

One final note for you: I've noticed that Garry's Mod for Linux does not handle symbolic links very well in the addons folder. Try extracting the ulx AND ulib (make sure you have ULib as well) folders into your addons folder directly.
