### ISSUE TITLE
[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by TheSkullHead** [Nayruden/Ulysses#532]
When i start my server, my physgun is black instead of red, and i can't press C or Q. As when i do, this happens:
[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Empty - lua/includes/extensions/table.lua:50
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:429
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/extensions/net.lua:32

[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Empty - lua/includes/extensions/table.lua:50
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:429
     4. func - addons/ulib/lua/ulib/client/cl_util.lua:22
      5. unknown - lua/includes/extensions/net.lua:32

What i've tried:
Restarting Server
Reinstalling ULX & Ulib

**Comment by SticklyMan** [comment]
Your xgui_client.lua file at line 129 does not match our most recent version. Could you try updating to the latest ULX and ULib from our repository? We're moving repositories, so look at this post to see the updated URLs:
http://forums.ulyssesmod.net/index.php/topic,9111.0.html
