### ISSUE TITLE
Error found in !Menu

### ISSUE THREAD

**Issue by LuckyJaspe** [Nayruden/Ulysses#535]
I been getting a "Something is making a script errors." 
When I bring up my menu it shows me a blank menu on all Cmd, Maps, and Settings. I probably messed with my Settings and broke something.
I get this:
[ERROR] lua/vgui/dpropertysheet.lua:100: attempt to index field 'Tab' (a nil value)
  1. UpdateColours - lua/vgui/dpropertysheet.lua:100
   2. ApplySchemeSettings - lua/vgui/dlabel.lua:78
    3. ApplySchemeSettings - lua/vgui/dpropertysheet.lua:121
     4. unknown - lua/vgui/dpropertysheet.lua:65
      5. InvalidateLayout - [C]:-1
       6. unknown - lua/vgui/dlabel.lua:121

**Comment by comedinha** [comment]
Try use new ulx and ulib
https://github.com/TeamUlysses/ulib
https://github.com/TeamUlysses/ulx
